/* This file is generated automatically by Design Sync. Do not edit this file directly. */

import { style } from "@vanilla-extract/css";

import { tokens } from "./contract.css";

/**
 * Code @xs Description
 */
export const largeRegularXs = style({
  fontFamily: "Kode Mono",
  fontSize: "1.125rem",
  fontWeight: "400",
  lineHeight: "1.25rem",
  letterSpacing: "0px",
});

/**
 * Code @sm Description
 */
export const largeRegularSm = style({
  fontFamily: "Kode Mono",
  fontSize: "1.125rem",
  fontWeight: "400",
  lineHeight: "1.25rem",
  letterSpacing: "0px",
});

/**
 * Code @md Description
 */
export const largeRegularMd = style({
  fontFamily: "Kode Mono",
  fontSize: "1.125rem",
  fontWeight: "400",
  lineHeight: "1.25rem",
  letterSpacing: "0px",
});

/**
 * Code @lg Description
 */
export const largeRegularLg = style({
  fontFamily: "Kode Mono",
  fontSize: "1.25rem",
  fontWeight: "400",
  lineHeight: "1.5rem",
  letterSpacing: "0px",
});

/**
 * Code @xl Description
 */
export const largeRegularXl = style({
  fontFamily: "Kode Mono",
  fontSize: "1.25rem",
  fontWeight: "400",
  lineHeight: "1.5rem",
  letterSpacing: "0px",
});

/**
 * Code @xxl Description
 */
export const largeRegularXxl = style({
  fontFamily: "Kode Mono",
  fontSize: "1.25rem",
  fontWeight: "400",
  lineHeight: "1.5rem",
  letterSpacing: "0px",
});

/**
 * Code Bold @ xs Description
 */
export const largeBoldXs = style({
  fontFamily: "Kode Mono",
  fontSize: "1.125rem",
  fontWeight: "500",
  lineHeight: "1.25rem",
  letterSpacing: "0px",
});

/**
 * Code Bold @ sm Description
 */
export const largeBoldSm = style({
  fontFamily: "Kode Mono",
  fontSize: "1.125rem",
  fontWeight: "500",
  lineHeight: "1.25rem",
  letterSpacing: "0px",
});

/**
 * Code Bold @ md Description
 */
export const largeBoldMd = style({
  fontFamily: "Kode Mono",
  fontSize: "1.125rem",
  fontWeight: "500",
  lineHeight: "1.25rem",
  letterSpacing: "0px",
});

/**
 * Code Bold @ lg Description
 */
export const largeBoldLg = style({
  fontFamily: "Kode Mono",
  fontSize: "1.25rem",
  fontWeight: "500",
  lineHeight: "1.5rem",
  letterSpacing: "0px",
});

/**
 * Code Bold @ xl Description
 */
export const largeBoldXl = style({
  fontFamily: "Kode Mono",
  fontSize: "1.25rem",
  fontWeight: "500",
  lineHeight: "1.5rem",
  letterSpacing: "0px",
});

/**
 * Code Bold @ xxl Description
 */
export const largeBoldXxl = style({
  fontFamily: "Kode Mono",
  fontSize: "1.25rem",
  fontWeight: "500",
  lineHeight: "1.5rem",
  letterSpacing: "0px",
});

/**
 * Small Code @xs Description
 */
export const smallRegularXs = style({
  fontFamily: "Kode Mono",
  fontSize: "0.75rem",
  fontWeight: "400",
  lineHeight: "1rem",
  letterSpacing: "0px",
});

/**
 * Small Code @sm Description
 */
export const smallRegularSm = style({
  fontFamily: "Kode Mono",
  fontSize: "0.75rem",
  fontWeight: "400",
  lineHeight: "1rem",
  letterSpacing: "0px",
});

/**
 * Small Code @md Description
 */
export const smallRegularMd = style({
  fontFamily: "Kode Mono",
  fontSize: "0.75rem",
  fontWeight: "400",
  lineHeight: "1rem",
  letterSpacing: "0px",
});

/**
 * Small Code @lg Description
 */
export const smallRegularLg = style({
  fontFamily: "Kode Mono",
  fontSize: "0.875rem",
  fontWeight: "400",
  lineHeight: "1rem",
  letterSpacing: "0px",
});

/**
 * Small Code @xl Description
 */
export const smallRegularXl = style({
  fontFamily: "Kode Mono",
  fontSize: "0.875rem",
  fontWeight: "400",
  lineHeight: "1rem",
  letterSpacing: "0px",
});

/**
 * Small Code @xxl Description
 */
export const smallRegularXxl = style({
  fontFamily: "Kode Mono",
  fontSize: "0.875rem",
  fontWeight: "400",
  lineHeight: "1rem",
  letterSpacing: "0px",
});

/**
 * Small Code Bold @ xs Description
 */
export const smallBoldXs = style({
  fontFamily: "Kode Mono",
  fontSize: "0.75rem",
  fontWeight: "700",
  lineHeight: "1rem",
  letterSpacing: "0px",
});

/**
 * Small Code Bold @ sm Description
 */
export const smallBoldSm = style({
  fontFamily: "Kode Mono",
  fontSize: "0.75rem",
  fontWeight: "700",
  lineHeight: "1rem",
  letterSpacing: "0px",
});

/**
 * Small Code Bold @ md Description
 */
export const smallBoldMd = style({
  fontFamily: "Kode Mono",
  fontSize: "0.75rem",
  fontWeight: "700",
  lineHeight: "1rem",
  letterSpacing: "0px",
});

/**
 * Small Code Bold @ lg Description
 */
export const smallBoldLg = style({
  fontFamily: "Kode Mono",
  fontSize: "0.875rem",
  fontWeight: "700",
  lineHeight: "1rem",
  letterSpacing: "0px",
});

/**
 * Small Code Bold @ xl Description
 */
export const smallBoldXl = style({
  fontFamily: "Kode Mono",
  fontSize: "0.875rem",
  fontWeight: "700",
  lineHeight: "1rem",
  letterSpacing: "0px",
});

/**
 * Small Code Bold @ xxl Description
 */
export const smallBoldXxl = style({
  fontFamily: "Kode Mono",
  fontSize: "0.875rem",
  fontWeight: "700",
  lineHeight: "1rem",
  letterSpacing: "0px",
});

/**
 * Smallest Code @xs Description
 */
export const smallestRegularXs = style({
  fontFamily: "Kode Mono",
  fontSize: "0.6875rem",
  fontWeight: "400",
  lineHeight: "0.875rem",
  letterSpacing: "0px",
});

/**
 * Smallest Code @sm Description
 */
export const smallestRegularSm = style({
  fontFamily: "Kode Mono",
  fontSize: "0.6875rem",
  fontWeight: "400",
  lineHeight: "0.875rem",
  letterSpacing: "0px",
});

/**
 * Smallest Code @md Description
 */
export const smallestRegularMd = style({
  fontFamily: "Kode Mono",
  fontSize: "0.6875rem",
  fontWeight: "400",
  lineHeight: "0.875rem",
  letterSpacing: "0px",
});

/**
 * Smallest Code @lg Description
 */
export const smallestRegularLg = style({
  fontFamily: "Kode Mono",
  fontSize: "0.75rem",
  fontWeight: "400",
  lineHeight: "1rem",
  letterSpacing: "0px",
});

/**
 * Smallest Code @xl Description
 */
export const smallestRegularXl = style({
  fontFamily: "Kode Mono",
  fontSize: "0.75rem",
  fontWeight: "400",
  lineHeight: "1rem",
  letterSpacing: "0px",
});

/**
 * Smallest Code @xxl Description
 */
export const smallestRegularXxl = style({
  fontFamily: "Kode Mono",
  fontSize: "0.75rem",
  fontWeight: "400",
  lineHeight: "1rem",
  letterSpacing: "0px",
});

/**
 * Smallest Code Bold @ xs Description
 */
export const smallestBoldXs = style({
  fontFamily: "Kode Mono",
  fontSize: "0.6875rem",
  fontWeight: "700",
  lineHeight: "0.875rem",
  letterSpacing: "0px",
});

/**
 * Smallest Code Bold @ sm Description
 */
export const smallestBoldSm = style({
  fontFamily: "Kode Mono",
  fontSize: "0.6875rem",
  fontWeight: "700",
  lineHeight: "0.875rem",
  letterSpacing: "0px",
});

/**
 * Smallest Code Bold @ md Description
 */
export const smallestBoldMd = style({
  fontFamily: "Kode Mono",
  fontSize: "0.6875rem",
  fontWeight: "700",
  lineHeight: "0.875rem",
  letterSpacing: "0px",
});

/**
 * Smallest Code Bold @ lg Description
 */
export const smallestBoldLg = style({
  fontFamily: "Kode Mono",
  fontSize: "0.75rem",
  fontWeight: "700",
  lineHeight: "1rem",
  letterSpacing: "0px",
});

/**
 * Smallest Code Bold @ xl Description
 */
export const smallestBoldXl = style({
  fontFamily: "Kode Mono",
  fontSize: "0.75rem",
  fontWeight: "700",
  lineHeight: "1rem",
  letterSpacing: "0px",
});

/**
 * Smallest Code Bold @ xxl Description
 */
export const smallestBoldXxl = style({
  fontFamily: "Kode Mono",
  fontSize: "0.75rem",
  fontWeight: "700",
  lineHeight: "1rem",
  letterSpacing: "0px",
});

/**
 * Code @xs Description
 */
export const baseRegularXs = style({
  fontFamily: "Kode Mono",
  fontSize: "0.875rem",
  fontWeight: "400",
  lineHeight: "1.125rem",
  letterSpacing: "0px",
});

/**
 * Code @sm Description
 */
export const baseRegularSm = style({
  fontFamily: "Kode Mono",
  fontSize: "0.875rem",
  fontWeight: "400",
  lineHeight: "1.125rem",
  letterSpacing: "0px",
});

/**
 * Code @md Description
 */
export const baseRegularMd = style({
  fontFamily: "Kode Mono",
  fontSize: "0.875rem",
  fontWeight: "400",
  lineHeight: "1.125rem",
  letterSpacing: "0px",
});

/**
 * Code @lg Description
 */
export const baseRegularLg = style({
  fontFamily: "Kode Mono",
  fontSize: "1rem",
  fontWeight: "400",
  lineHeight: "1.25rem",
  letterSpacing: "0px",
});

/**
 * Code @xl Description
 */
export const baseRegularXl = style({
  fontFamily: "Kode Mono",
  fontSize: "1rem",
  fontWeight: "400",
  lineHeight: "1.25rem",
  letterSpacing: "0px",
});

/**
 * Code @xxl Description
 */
export const baseRegularXxl = style({
  fontFamily: "Kode Mono",
  fontSize: "1rem",
  fontWeight: "400",
  lineHeight: "1.25rem",
  letterSpacing: "0px",
});

/**
 * Code Bold @ xs Description
 */
export const baseBoldXs = style({
  fontFamily: "Kode Mono",
  fontSize: "0.875rem",
  fontWeight: "700",
  lineHeight: "1.125rem",
  letterSpacing: "0px",
});

/**
 * Code Bold @ sm Description
 */
export const baseBoldSm = style({
  fontFamily: "Kode Mono",
  fontSize: "0.875rem",
  fontWeight: "700",
  lineHeight: "1.125rem",
  letterSpacing: "0px",
});

/**
 * Code Bold @ md Description
 */
export const baseBoldMd = style({
  fontFamily: "Kode Mono",
  fontSize: "0.875rem",
  fontWeight: "700",
  lineHeight: "1.125rem",
  letterSpacing: "0px",
});

/**
 * Code Bold @ lg Description
 */
export const baseBoldLg = style({
  fontFamily: "Kode Mono",
  fontSize: "1rem",
  fontWeight: "700",
  lineHeight: "1.25rem",
  letterSpacing: "0px",
});

/**
 * Code Bold @ xl Description
 */
export const baseBoldXl = style({
  fontFamily: "Kode Mono",
  fontSize: "1rem",
  fontWeight: "700",
  lineHeight: "1.25rem",
  letterSpacing: "0px",
});

/**
 * Code Bold @ xxl Description
 */
export const baseBoldXxl = style({
  fontFamily: "Kode Mono",
  fontSize: "1rem",
  fontWeight: "700",
  lineHeight: "1.25rem",
  letterSpacing: "0px",
});

/**
 * H1 Description
 */
export const fontH1Xs = style({
  fontFamily: "Inter",
  fontSize: "2rem",
  fontWeight: "500",
  lineHeight: "2.25rem",
  letterSpacing: "0px",
});

/**
 * H1 Description
 */
export const fontH1Sm = style({
  fontFamily: "Inter",
  fontSize: "2rem",
  fontWeight: "500",
  lineHeight: "2.25rem",
  letterSpacing: "0px",
});

/**
 * H1 Description
 */
export const fontH1Md = style({
  fontFamily: "Inter",
  fontSize: "2rem",
  fontWeight: "500",
  lineHeight: "2.25rem",
  letterSpacing: "0px",
});

/**
 * H1 Description
 */
export const fontH1Lg = style({
  fontFamily: "Inter",
  fontSize: "2.5rem",
  fontWeight: "500",
  lineHeight: "3rem",
  letterSpacing: "0px",
});

/**
 * H1 Description
 */
export const fontH1Xl = style({
  fontFamily: "Inter",
  fontSize: "2.5rem",
  fontWeight: "500",
  lineHeight: "3rem",
  letterSpacing: "0px",
});

/**
 * H1 Description
 */
export const fontH1Xxl = style({
  fontFamily: "Inter",
  fontSize: "2.5rem",
  fontWeight: "500",
  lineHeight: "3rem",
  letterSpacing: "0px",
});

/**
 * H2 Description
 */
export const fontH2Xs = style({
  fontFamily: "Inter",
  fontSize: "1.75rem",
  fontWeight: "500",
  lineHeight: "2rem",
  letterSpacing: "0px",
});

/**
 * H2 Description
 */
export const fontH2Sm = style({
  fontFamily: "Inter",
  fontSize: "1.75rem",
  fontWeight: "500",
  lineHeight: "2rem",
  letterSpacing: "0px",
});

/**
 * H2 Description
 */
export const fontH2Md = style({
  fontFamily: "Inter",
  fontSize: "1.75rem",
  fontWeight: "500",
  lineHeight: "2rem",
  letterSpacing: "0px",
});

/**
 * H2 Description
 */
export const fontH2Lg = style({
  fontFamily: "Inter",
  fontSize: "2rem",
  fontWeight: "500",
  lineHeight: "2.25rem",
  letterSpacing: "0px",
});

/**
 * H2 Description
 */
export const fontH2Xl = style({
  fontFamily: "Inter",
  fontSize: "2rem",
  fontWeight: "500",
  lineHeight: "2.25rem",
  letterSpacing: "0px",
});

/**
 * H2 Description
 */
export const fontH2Xxl = style({
  fontFamily: "Inter",
  fontSize: "2rem",
  fontWeight: "500",
  lineHeight: "2.25rem",
  letterSpacing: "0px",
});

/**
 * H3 Description
 */
export const fontH3Xs = style({
  fontFamily: "Inter",
  fontSize: "1.5rem",
  fontWeight: "500",
  lineHeight: "1.75rem",
  letterSpacing: "0px",
});

/**
 * H3 Description
 */
export const fontH3Sm = style({
  fontFamily: "Inter",
  fontSize: "1.5rem",
  fontWeight: "500",
  lineHeight: "1.75rem",
  letterSpacing: "0px",
});

/**
 * H3 Description
 */
export const fontH3Md = style({
  fontFamily: "Inter",
  fontSize: "1.5rem",
  fontWeight: "500",
  lineHeight: "1.75rem",
  letterSpacing: "0px",
});

/**
 * H3 Description
 */
export const fontH3Lg = style({
  fontFamily: "Inter",
  fontSize: "1.75rem",
  fontWeight: "500",
  lineHeight: "2rem",
  letterSpacing: "0px",
});

/**
 * H3 Description
 */
export const fontH3Xl = style({
  fontFamily: "Inter",
  fontSize: "1.75rem",
  fontWeight: "500",
  lineHeight: "2rem",
  letterSpacing: "0px",
});

/**
 * H3 Description
 */
export const fontH3Xxl = style({
  fontFamily: "Inter",
  fontSize: "1.75rem",
  fontWeight: "500",
  lineHeight: "2rem",
  letterSpacing: "0px",
});

/**
 * H4 Description
 */
export const fontH4Xs = style({
  fontFamily: "Inter",
  fontSize: "1.25rem",
  fontWeight: "500",
  lineHeight: "1.5rem",
  letterSpacing: "0px",
});

/**
 * H4 Description
 */
export const fontH4Sm = style({
  fontFamily: "Inter",
  fontSize: "1.25rem",
  fontWeight: "500",
  lineHeight: "1.5rem",
  letterSpacing: "0px",
});

/**
 * H4 Description
 */
export const fontH4Md = style({
  fontFamily: "Inter",
  fontSize: "1.25rem",
  fontWeight: "500",
  lineHeight: "1.5rem",
  letterSpacing: "0px",
});

/**
 * H4 Description
 */
export const fontH4Lg = style({
  fontFamily: "Inter",
  fontSize: "1.5rem",
  fontWeight: "500",
  lineHeight: "1.75rem",
  letterSpacing: "0px",
});

/**
 * H4 Description
 */
export const fontH4Xl = style({
  fontFamily: "Inter",
  fontSize: "1.5rem",
  fontWeight: "500",
  lineHeight: "1.75rem",
  letterSpacing: "0px",
});

/**
 * H4 Description
 */
export const fontH4Xxl = style({
  fontFamily: "Inter",
  fontSize: "1.5rem",
  fontWeight: "500",
  lineHeight: "1.75rem",
  letterSpacing: "0px",
});

/**
 * H5 Description
 */
export const fontH5Xs = style({
  fontFamily: "Inter",
  fontSize: "1rem",
  fontWeight: "500",
  lineHeight: "1.25rem",
  letterSpacing: "0px",
});

/**
 * H5 Description
 */
export const fontH5Sm = style({
  fontFamily: "Inter",
  fontSize: "1rem",
  fontWeight: "500",
  lineHeight: "1.25rem",
  letterSpacing: "0px",
});

/**
 * H5 Description
 */
export const fontH5Md = style({
  fontFamily: "Inter",
  fontSize: "1rem",
  fontWeight: "500",
  lineHeight: "1.25rem",
  letterSpacing: "0px",
});

/**
 * H5 Description
 */
export const fontH5Lg = style({
  fontFamily: "Inter",
  fontSize: "1.25rem",
  fontWeight: "500",
  lineHeight: "1.5rem",
  letterSpacing: "0px",
});

/**
 * H5 Description
 */
export const fontH5Xl = style({
  fontFamily: "Inter",
  fontSize: "1.25rem",
  fontWeight: "500",
  lineHeight: "1.5rem",
  letterSpacing: "0px",
});

/**
 * H5 Description
 */
export const fontH5Xxl = style({
  fontFamily: "Inter",
  fontSize: "1.25rem",
  fontWeight: "500",
  lineHeight: "1.5rem",
  letterSpacing: "0px",
});

/**
 * H6 Description
 */
export const fontH6Xs = style({
  fontFamily: "Inter",
  fontSize: "0.875rem",
  fontWeight: "500",
  lineHeight: "1.125rem",
  letterSpacing: "0px",
});

/**
 * H6 Description
 */
export const fontH6Sm = style({
  fontFamily: "Inter",
  fontSize: "0.875rem",
  fontWeight: "500",
  lineHeight: "1.125rem",
  letterSpacing: "0px",
});

/**
 * H6 Description
 */
export const fontH6Md = style({
  fontFamily: "Inter",
  fontSize: "0.875rem",
  fontWeight: "500",
  lineHeight: "1.125rem",
  letterSpacing: "0px",
});

/**
 * H6 Description
 */
export const fontH6Lg = style({
  fontFamily: "Inter",
  fontSize: "1rem",
  fontWeight: "500",
  lineHeight: "1.25rem",
  letterSpacing: "0px",
});

/**
 * H6 Description
 */
export const fontH6Xl = style({
  fontFamily: "Inter",
  fontSize: "1rem",
  fontWeight: "500",
  lineHeight: "1.25rem",
  letterSpacing: "0px",
});

/**
 * H6 Description
 */
export const fontH6Xxl = style({
  fontFamily: "Inter",
  fontSize: "1rem",
  fontWeight: "500",
  lineHeight: "1.25rem",
  letterSpacing: "0px",
});

/**
 * Input Element Code @xs Description
 */
export const baseRegularXs = style({
  fontFamily: "Kode Mono",
  fontSize: "0.75rem",
  fontWeight: "400",
  lineHeight: "1rem",
  letterSpacing: "0px",
});

/**
 * Input Element Code @sm Description
 */
export const baseRegularSm = style({
  fontFamily: "Kode Mono",
  fontSize: "0.875rem",
  fontWeight: "400",
  lineHeight: "1.125rem",
  letterSpacing: "0px",
});

/**
 * Input Element Code @md Description
 */
export const baseRegularMd = style({
  fontFamily: "Kode Mono",
  fontSize: "1rem",
  fontWeight: "400",
  lineHeight: "1.25rem",
  letterSpacing: "0px",
});

/**
 * Input Element Code @lg Description
 */
export const baseRegularLg = style({
  fontFamily: "Kode Mono",
  fontSize: "1rem",
  fontWeight: "400",
  lineHeight: "1.25rem",
  letterSpacing: "0px",
});

/**
 * Input Element Code @xl Description
 */
export const baseRegularXl = style({
  fontFamily: "Kode Mono",
  fontSize: "1rem",
  fontWeight: "400",
  lineHeight: "1.25rem",
  letterSpacing: "0px",
});

/**
 * Input Element Code @xxl Description
 */
export const baseRegularXxl = style({
  fontFamily: "Kode Mono",
  fontSize: "1rem",
  fontWeight: "400",
  lineHeight: "1.25rem",
  letterSpacing: "0px",
});

/**
 * Input Element Code @xs Description
 */
export const mobileRegularXs = style({
  fontFamily: "Kode Mono",
  fontSize: "1rem",
  fontWeight: "400",
  lineHeight: "1.25rem",
  letterSpacing: "0px",
});

/**
 * Input Element Code @sm Description
 */
export const mobileRegularSm = style({
  fontFamily: "Kode Mono",
  fontSize: "1rem",
  fontWeight: "400",
  lineHeight: "1.25rem",
  letterSpacing: "0px",
});

/**
 * Input Element Code @md Description
 */
export const mobileRegularMd = style({
  fontFamily: "Kode Mono",
  fontSize: "1rem",
  fontWeight: "400",
  lineHeight: "1.25rem",
  letterSpacing: "0px",
});

/**
 * Input Element Code @lg Description
 */
export const mobileRegularLg = style({
  fontFamily: "Kode Mono",
  fontSize: "1rem",
  fontWeight: "400",
  lineHeight: "1.25rem",
  letterSpacing: "0px",
});

/**
 * Input Element Code @xl Description
 */
export const mobileRegularXl = style({
  fontFamily: "Kode Mono",
  fontSize: "1rem",
  fontWeight: "400",
  lineHeight: "1.25rem",
  letterSpacing: "0px",
});

/**
 * Input Element Code @xxl Description
 */
export const mobileRegularXxl = style({
  fontFamily: "Kode Mono",
  fontSize: "1rem",
  fontWeight: "400",
  lineHeight: "1.25rem",
  letterSpacing: "0px",
});

/**
 * Input Element @xs Description
 */
export const baseRegularXs = style({
  fontFamily: "Inter",
  fontSize: "0.75rem",
  fontWeight: "400",
  lineHeight: "1rem",
  letterSpacing: "0px",
});

/**
 * Input Element @sm Description
 */
export const baseRegularSm = style({
  fontFamily: "Inter",
  fontSize: "0.875rem",
  fontWeight: "400",
  lineHeight: "1.375rem",
  letterSpacing: "0px",
});

/**
 * Input Element @md Description
 */
export const baseRegularMd = style({
  fontFamily: "Inter",
  fontSize: "1rem",
  fontWeight: "400",
  lineHeight: "1.5rem",
  letterSpacing: "0px",
});

/**
 * Input Element @lg Description
 */
export const baseRegularLg = style({
  fontFamily: "Inter",
  fontSize: "1rem",
  fontWeight: "400",
  lineHeight: "1.5rem",
  letterSpacing: "0px",
});

/**
 * Input Element @xl Description
 */
export const baseRegularXl = style({
  fontFamily: "Inter",
  fontSize: "1rem",
  fontWeight: "400",
  lineHeight: "1.5rem",
  letterSpacing: "0px",
});

/**
 * Input Element @xxl Description
 */
export const baseRegularXxl = style({
  fontFamily: "Inter",
  fontSize: "1rem",
  fontWeight: "400",
  lineHeight: "1.5rem",
  letterSpacing: "0px",
});

/**
 * Input Element @xs Description
 */
export const mobileRegularXs = style({
  fontFamily: "Inter",
  fontSize: "1rem",
  fontWeight: "400",
  lineHeight: "1.5rem",
  letterSpacing: "0px",
});

/**
 * Input Element @sm Description
 */
export const mobileRegularSm = style({
  fontFamily: "Inter",
  fontSize: "1rem",
  fontWeight: "400",
  lineHeight: "1.5rem",
  letterSpacing: "0px",
});

/**
 * Input Element @md Description
 */
export const mobileRegularMd = style({
  fontFamily: "Inter",
  fontSize: "1rem",
  fontWeight: "400",
  lineHeight: "1.5rem",
  letterSpacing: "0px",
});

/**
 * Input Element @lg Description
 */
export const mobileRegularLg = style({
  fontFamily: "Inter",
  fontSize: "1rem",
  fontWeight: "400",
  lineHeight: "1.5rem",
  letterSpacing: "0px",
});

/**
 * Input Element @xl Description
 */
export const mobileRegularXl = style({
  fontFamily: "Inter",
  fontSize: "1rem",
  fontWeight: "400",
  lineHeight: "1.5rem",
  letterSpacing: "0px",
});

/**
 * Input Element @xxl Description
 */
export const mobileRegularXxl = style({
  fontFamily: "Inter",
  fontSize: "1rem",
  fontWeight: "400",
  lineHeight: "1.5rem",
  letterSpacing: "0px",
});

/**
 * Small P @xs Description
 */
export const smallRegularXs = style({
  fontFamily: "Inter",
  fontSize: "0.75rem",
  fontWeight: "400",
  lineHeight: "1rem",
  letterSpacing: "0px",
});

/**
 * Small P @sm Description
 */
export const smallRegularSm = style({
  fontFamily: "Inter",
  fontSize: "0.75rem",
  fontWeight: "400",
  lineHeight: "1rem",
  letterSpacing: "0px",
});

/**
 * Small P @md Description
 */
export const smallRegularMd = style({
  fontFamily: "Inter",
  fontSize: "0.75rem",
  fontWeight: "400",
  lineHeight: "1rem",
  letterSpacing: "0px",
});

/**
 * Small P @lg Description
 */
export const smallRegularLg = style({
  fontFamily: "Inter",
  fontSize: "0.875rem",
  fontWeight: "400",
  lineHeight: "1.375rem",
  letterSpacing: "0px",
});

/**
 * Small P @xl Description
 */
export const smallRegularXl = style({
  fontFamily: "Inter",
  fontSize: "0.875rem",
  fontWeight: "400",
  lineHeight: "1.375rem",
  letterSpacing: "0px",
});

/**
 * Small P @xxl Description
 */
export const smallRegularXxl = style({
  fontFamily: "Inter",
  fontSize: "0.875rem",
  fontWeight: "400",
  lineHeight: "1.375rem",
  letterSpacing: "0px",
});

/**
 * Small P Bold @ xs Description
 */
export const smallBoldXs = style({
  fontFamily: "Inter",
  fontSize: "0.75rem",
  fontWeight: "500",
  lineHeight: "1rem",
  letterSpacing: "0px",
});

/**
 * Small P Bold @ sm Description
 */
export const smallBoldSm = style({
  fontFamily: "Inter",
  fontSize: "0.75rem",
  fontWeight: "500",
  lineHeight: "1rem",
  letterSpacing: "0px",
});

/**
 * Small P Bold @ md Description
 */
export const smallBoldMd = style({
  fontFamily: "Inter",
  fontSize: "0.75rem",
  fontWeight: "500",
  lineHeight: "1rem",
  letterSpacing: "0px",
});

/**
 * Small P Bold @ lg Description
 */
export const smallBoldLg = style({
  fontFamily: "Inter",
  fontSize: "0.875rem",
  fontWeight: "500",
  lineHeight: "1.375rem",
  letterSpacing: "0px",
});

/**
 * Small P Bold @ xl Description
 */
export const smallBoldXl = style({
  fontFamily: "Inter",
  fontSize: "0.875rem",
  fontWeight: "500",
  lineHeight: "1.375rem",
  letterSpacing: "0px",
});

/**
 * Small P Bold @ xxl Description
 */
export const smallBoldXxl = style({
  fontFamily: "Inter",
  fontSize: "0.875rem",
  fontWeight: "500",
  lineHeight: "1.375rem",
  letterSpacing: "0px",
});

/**
 * Smallest P @xs Description
 */
export const smallestRegularXs = style({
  fontFamily: "Inter",
  fontSize: "0.6875rem",
  fontWeight: "400",
  lineHeight: "1rem",
  letterSpacing: "0px",
});

/**
 * Smallest P @sm Description
 */
export const smallestRegularSm = style({
  fontFamily: "Inter",
  fontSize: "0.6875rem",
  fontWeight: "400",
  lineHeight: "1rem",
  letterSpacing: "0px",
});

/**
 * Smallest P @md Description
 */
export const smallestRegularMd = style({
  fontFamily: "Inter",
  fontSize: "0.6875rem",
  fontWeight: "400",
  lineHeight: "1rem",
  letterSpacing: "0px",
});

/**
 * Smallest P @lg Description
 */
export const smallestRegularLg = style({
  fontFamily: "Inter",
  fontSize: "0.75rem",
  fontWeight: "400",
  lineHeight: "1.25rem",
  letterSpacing: "0px",
});

/**
 * Smallest P @xl Description
 */
export const smallestRegularXl = style({
  fontFamily: "Inter",
  fontSize: "0.75rem",
  fontWeight: "400",
  lineHeight: "1.25rem",
  letterSpacing: "0px",
});

/**
 * Smallest P @xxl Description
 */
export const smallestRegularXxl = style({
  fontFamily: "Inter",
  fontSize: "0.75rem",
  fontWeight: "400",
  lineHeight: "1.25rem",
  letterSpacing: "0px",
});

/**
 * Smallest P Bold @ xs Description
 */
export const smallestBoldXs = style({
  fontFamily: "Inter",
  fontSize: "0.6875rem",
  fontWeight: "500",
  lineHeight: "1rem",
  letterSpacing: "0px",
});

/**
 * Smallest P Bold @ sm Description
 */
export const smallestBoldSm = style({
  fontFamily: "Inter",
  fontSize: "0.6875rem",
  fontWeight: "500",
  lineHeight: "1rem",
  letterSpacing: "0px",
});

/**
 * Smallest P Bold @ md Description
 */
export const smallestBoldMd = style({
  fontFamily: "Inter",
  fontSize: "0.6875rem",
  fontWeight: "500",
  lineHeight: "1rem",
  letterSpacing: "0px",
});

/**
 * Smallest P Bold @ lg Description
 */
export const smallestBoldLg = style({
  fontFamily: "Inter",
  fontSize: "0.75rem",
  fontWeight: "500",
  lineHeight: "1.25rem",
  letterSpacing: "0px",
});

/**
 * Smallest P Bold @ xl Description
 */
export const smallestBoldXl = style({
  fontFamily: "Inter",
  fontSize: "0.75rem",
  fontWeight: "500",
  lineHeight: "1.25rem",
  letterSpacing: "0px",
});

/**
 * Smallest P Bold @ xxl Description
 */
export const smallestBoldXxl = style({
  fontFamily: "Inter",
  fontSize: "0.75rem",
  fontWeight: "500",
  lineHeight: "1.25rem",
  letterSpacing: "0px",
});

/**
 * P @xs Description
 */
export const baseRegularXs = style({
  fontFamily: "Inter",
  fontSize: "0.875rem",
  fontWeight: "400",
  lineHeight: "1.375rem",
  letterSpacing: "0px",
});

/**
 * P @sm Description
 */
export const baseRegularSm = style({
  fontFamily: "Inter",
  fontSize: "0.875rem",
  fontWeight: "400",
  lineHeight: "1.375rem",
  letterSpacing: "0px",
});

/**
 * P @md Description
 */
export const baseRegularMd = style({
  fontFamily: "Inter",
  fontSize: "0.875rem",
  fontWeight: "400",
  lineHeight: "1.375rem",
  letterSpacing: "0px",
});

/**
 * P @lg Description
 */
export const baseRegularLg = style({
  fontFamily: "Inter",
  fontSize: "1rem",
  fontWeight: "400",
  lineHeight: "1.5rem",
  letterSpacing: "0px",
});

/**
 * P @xl Description
 */
export const baseRegularXl = style({
  fontFamily: "Inter",
  fontSize: "1rem",
  fontWeight: "400",
  lineHeight: "1.5rem",
  letterSpacing: "0px",
});

/**
 * P @xxl Description
 */
export const baseRegularXxl = style({
  fontFamily: "Inter",
  fontSize: "1rem",
  fontWeight: "400",
  lineHeight: "1.5rem",
  letterSpacing: "0px",
});

/**
 * P Bold @ xs Description
 */
export const baseBoldXs = style({
  fontFamily: "Inter",
  fontSize: "0.875rem",
  fontWeight: "500",
  lineHeight: "1.375rem",
  letterSpacing: "0px",
});

/**
 * P Bold @ sm Description
 */
export const baseBoldSm = style({
  fontFamily: "Inter",
  fontSize: "0.875rem",
  fontWeight: "500",
  lineHeight: "1.375rem",
  letterSpacing: "0px",
});

/**
 * P Bold @ md Description
 */
export const baseBoldMd = style({
  fontFamily: "Inter",
  fontSize: "0.875rem",
  fontWeight: "500",
  lineHeight: "1.375rem",
  letterSpacing: "0px",
});

/**
 * P Bold @ lg Description
 */
export const baseBoldLg = style({
  fontFamily: "Inter",
  fontSize: "1rem",
  fontWeight: "500",
  lineHeight: "1.5rem",
  letterSpacing: "0px",
});

/**
 * P Bold @ xl Description
 */
export const baseBoldXl = style({
  fontFamily: "Inter",
  fontSize: "1rem",
  fontWeight: "500",
  lineHeight: "1.5rem",
  letterSpacing: "0px",
});

/**
 * P Bold @ xxl Description
 */
export const baseBoldXxl = style({
  fontFamily: "Inter",
  fontSize: "1rem",
  fontWeight: "500",
  lineHeight: "1.5rem",
  letterSpacing: "0px",
});

/**
 * P Large @xs Description
 */
export const largeRegularXs = style({
  fontFamily: "Inter",
  fontSize: "1.125rem",
  fontWeight: "400",
  lineHeight: "1.25rem",
  letterSpacing: "0px",
});

/**
 * P Large @sm Description
 */
export const largeRegularSm = style({
  fontFamily: "Inter",
  fontSize: "1.125rem",
  fontWeight: "400",
  lineHeight: "1.25rem",
  letterSpacing: "0px",
});

/**
 * P Large @md Description
 */
export const largeRegularMd = style({
  fontFamily: "Inter",
  fontSize: "1.125rem",
  fontWeight: "400",
  lineHeight: "1.25rem",
  letterSpacing: "0px",
});

/**
 * P Large @lg Description
 */
export const largeRegularLg = style({
  fontFamily: "Inter",
  fontSize: "1.25rem",
  fontWeight: "400",
  lineHeight: "1.5rem",
  letterSpacing: "0px",
});

/**
 * P Large @xl Description
 */
export const largeRegularXl = style({
  fontFamily: "Inter",
  fontSize: "1.25rem",
  fontWeight: "400",
  lineHeight: "1.5rem",
  letterSpacing: "0px",
});

/**
 * P Large @xxl Description
 */
export const largeRegularXxl = style({
  fontFamily: "Inter",
  fontSize: "1.25rem",
  fontWeight: "400",
  lineHeight: "1.5rem",
  letterSpacing: "0px",
});

/**
 * P Bold @ xs Description
 */
export const largeBoldXs = style({
  fontFamily: "Inter",
  fontSize: "1.125rem",
  fontWeight: "500",
  lineHeight: "1.25rem",
  letterSpacing: "0px",
});

/**
 * P Bold @ sm Description
 */
export const largeBoldSm = style({
  fontFamily: "Inter",
  fontSize: "1.125rem",
  fontWeight: "500",
  lineHeight: "1.25rem",
  letterSpacing: "0px",
});

/**
 * P Bold @ md Description
 */
export const largeBoldMd = style({
  fontFamily: "Inter",
  fontSize: "1.125rem",
  fontWeight: "500",
  lineHeight: "1.25rem",
  letterSpacing: "0px",
});

/**
 * P Bold @ lg Description
 */
export const largeBoldLg = style({
  fontFamily: "Inter",
  fontSize: "1.25rem",
  fontWeight: "500",
  lineHeight: "1.5rem",
  letterSpacing: "0px",
});

/**
 * P Bold @ xl Description
 */
export const largeBoldXl = style({
  fontFamily: "Inter",
  fontSize: "1.25rem",
  fontWeight: "500",
  lineHeight: "1.5rem",
  letterSpacing: "0px",
});

/**
 * P Bold @ xxl Description
 */
export const largeBoldXxl = style({
  fontFamily: "Inter",
  fontSize: "1.25rem",
  fontWeight: "500",
  lineHeight: "1.5rem",
  letterSpacing: "0px",
});

/**
 * Small P @xs Description
 */
export const smallRegularXs = style({
  fontFamily: "Inter",
  fontSize: "0.75rem",
  fontWeight: "400",
  lineHeight: "1rem",
  letterSpacing: "0px",
});

/**
 * Small P @sm Description
 */
export const smallRegularSm = style({
  fontFamily: "Inter",
  fontSize: "0.75rem",
  fontWeight: "400",
  lineHeight: "1rem",
  letterSpacing: "0px",
});

/**
 * Small P @md Description
 */
export const smallRegularMd = style({
  fontFamily: "Inter",
  fontSize: "0.75rem",
  fontWeight: "400",
  lineHeight: "1rem",
  letterSpacing: "0px",
});

/**
 * Small P @lg Description
 */
export const smallRegularLg = style({
  fontFamily: "Inter",
  fontSize: "0.875rem",
  fontWeight: "400",
  lineHeight: "1rem",
  letterSpacing: "0px",
});

/**
 * Small P @xl Description
 */
export const smallRegularXl = style({
  fontFamily: "Inter",
  fontSize: "0.875rem",
  fontWeight: "400",
  lineHeight: "1rem",
  letterSpacing: "0px",
});

/**
 * Small P @xxl Description
 */
export const smallRegularXxl = style({
  fontFamily: "Inter",
  fontSize: "0.875rem",
  fontWeight: "400",
  lineHeight: "1rem",
  letterSpacing: "0px",
});

/**
 * Small P Bold @ xs Description
 */
export const smallBoldXs = style({
  fontFamily: "Inter",
  fontSize: "0.75rem",
  fontWeight: "500",
  lineHeight: "1rem",
  letterSpacing: "0px",
});

/**
 * Small P Bold @ sm Description
 */
export const smallBoldSm = style({
  fontFamily: "Inter",
  fontSize: "0.75rem",
  fontWeight: "500",
  lineHeight: "1rem",
  letterSpacing: "0px",
});

/**
 * Small P Bold @ md Description
 */
export const smallBoldMd = style({
  fontFamily: "Inter",
  fontSize: "0.75rem",
  fontWeight: "500",
  lineHeight: "1rem",
  letterSpacing: "0px",
});

/**
 * Small P Bold @ lg Description
 */
export const smallBoldLg = style({
  fontFamily: "Inter",
  fontSize: "0.875rem",
  fontWeight: "500",
  lineHeight: "1rem",
  letterSpacing: "0px",
});

/**
 * Small P Bold @ xl Description
 */
export const smallBoldXl = style({
  fontFamily: "Inter",
  fontSize: "0.875rem",
  fontWeight: "500",
  lineHeight: "1rem",
  letterSpacing: "0px",
});

/**
 * Small P Bold @ xxl Description
 */
export const smallBoldXxl = style({
  fontFamily: "Inter",
  fontSize: "0.875rem",
  fontWeight: "500",
  lineHeight: "1rem",
  letterSpacing: "0px",
});

/**
 * Smallest P @xs Description
 */
export const smallestRegularXs = style({
  fontFamily: "Inter",
  fontSize: "0.6875rem",
  fontWeight: "400",
  lineHeight: "0.875rem",
  letterSpacing: "0px",
});

/**
 * Smallest P @sm Description
 */
export const smallestRegularSm = style({
  fontFamily: "Inter",
  fontSize: "0.6875rem",
  fontWeight: "400",
  lineHeight: "0.875rem",
  letterSpacing: "0px",
});

/**
 * Smallest P @md Description
 */
export const smallestRegularMd = style({
  fontFamily: "Inter",
  fontSize: "0.6875rem",
  fontWeight: "400",
  lineHeight: "0.875rem",
  letterSpacing: "0px",
});

/**
 * Smallest P @lg Description
 */
export const smallestRegularLg = style({
  fontFamily: "Inter",
  fontSize: "0.75rem",
  fontWeight: "400",
  lineHeight: "1rem",
  letterSpacing: "0px",
});

/**
 * Smallest P @xl Description
 */
export const smallestRegularXl = style({
  fontFamily: "Inter",
  fontSize: "0.75rem",
  fontWeight: "400",
  lineHeight: "1rem",
  letterSpacing: "0px",
});

/**
 * Smallest P @xxl Description
 */
export const smallestRegularXxl = style({
  fontFamily: "Inter",
  fontSize: "0.75rem",
  fontWeight: "400",
  lineHeight: "1rem",
  letterSpacing: "0px",
});

/**
 * Smallest P Bold @ xs Description
 */
export const smallestBoldXs = style({
  fontFamily: "Inter",
  fontSize: "0.6875rem",
  fontWeight: "500",
  lineHeight: "0.875rem",
  letterSpacing: "0px",
});

/**
 * Smallest P Bold @ sm Description
 */
export const smallestBoldSm = style({
  fontFamily: "Inter",
  fontSize: "0.6875rem",
  fontWeight: "500",
  lineHeight: "0.875rem",
  letterSpacing: "0px",
});

/**
 * Smallest P Bold @ md Description
 */
export const smallestBoldMd = style({
  fontFamily: "Inter",
  fontSize: "0.6875rem",
  fontWeight: "500",
  lineHeight: "0.875rem",
  letterSpacing: "0px",
});

/**
 * Smallest P Bold @ lg Description
 */
export const smallestBoldLg = style({
  fontFamily: "Inter",
  fontSize: "0.75rem",
  fontWeight: "500",
  lineHeight: "1rem",
  letterSpacing: "0px",
});

/**
 * Smallest P Bold @ xl Description
 */
export const smallestBoldXl = style({
  fontFamily: "Inter",
  fontSize: "0.75rem",
  fontWeight: "500",
  lineHeight: "1rem",
  letterSpacing: "0px",
});

/**
 * Smallest P Bold @ xxl Description
 */
export const smallestBoldXxl = style({
  fontFamily: "Inter",
  fontSize: "0.75rem",
  fontWeight: "500",
  lineHeight: "1rem",
  letterSpacing: "0px",
});

/**
 * P @xs Description
 */
export const baseRegularXs = style({
  fontFamily: "Inter",
  fontSize: "0.875rem",
  fontWeight: "400",
  lineHeight: "1.125rem",
  letterSpacing: "0px",
});

/**
 * P @sm Description
 */
export const baseRegularSm = style({
  fontFamily: "Inter",
  fontSize: "0.875rem",
  fontWeight: "400",
  lineHeight: "1.125rem",
  letterSpacing: "0px",
});

/**
 * P @md Description
 */
export const baseRegularMd = style({
  fontFamily: "Inter",
  fontSize: "0.875rem",
  fontWeight: "400",
  lineHeight: "1.125rem",
  letterSpacing: "0px",
});

/**
 * P @lg Description
 */
export const baseRegularLg = style({
  fontFamily: "Inter",
  fontSize: "1rem",
  fontWeight: "400",
  lineHeight: "1.25rem",
  letterSpacing: "0px",
});

/**
 * P @xl Description
 */
export const baseRegularXl = style({
  fontFamily: "Inter",
  fontSize: "1rem",
  fontWeight: "400",
  lineHeight: "1.25rem",
  letterSpacing: "0px",
});

/**
 * P @xxl Description
 */
export const baseRegularXxl = style({
  fontFamily: "Inter",
  fontSize: "1rem",
  fontWeight: "400",
  lineHeight: "1.25rem",
  letterSpacing: "0px",
});

/**
 * P Bold @ xs Description
 */
export const baseBoldXs = style({
  fontFamily: "Inter",
  fontSize: "0.875rem",
  fontWeight: "500",
  lineHeight: "1.125rem",
  letterSpacing: "0px",
});

/**
 * P Bold @ sm Description
 */
export const baseBoldSm = style({
  fontFamily: "Inter",
  fontSize: "0.875rem",
  fontWeight: "500",
  lineHeight: "1.125rem",
  letterSpacing: "0px",
});

/**
 * P Bold @ md Description
 */
export const baseBoldMd = style({
  fontFamily: "Inter",
  fontSize: "0.875rem",
  fontWeight: "500",
  lineHeight: "1.125rem",
  letterSpacing: "0px",
});

/**
 * P Bold @ lg Description
 */
export const baseBoldLg = style({
  fontFamily: "Inter",
  fontSize: "1rem",
  fontWeight: "500",
  lineHeight: "1.25rem",
  letterSpacing: "0px",
});

/**
 * P Bold @ xl Description
 */
export const baseBoldXl = style({
  fontFamily: "Inter",
  fontSize: "1rem",
  fontWeight: "500",
  lineHeight: "1.25rem",
  letterSpacing: "0px",
});

/**
 * P Bold @ xxl Description
 */
export const baseBoldXxl = style({
  fontFamily: "Inter",
  fontSize: "1rem",
  fontWeight: "500",
  lineHeight: "1.25rem",
  letterSpacing: "0px",
});
