const bgflat = {
  brand: 'var(--figma-color-bg-brand)',
  brandHover: 'var(--figma-color-bg-brand-hover)',
  brandPressed: 'var(--figma-color-bg-brand-pressed)',
  brandSecondary: 'var(--figma-color-bg-brand-secondary)',
  brandTertiary: 'var(--figma-color-bg-brand-tertiary)',
  component: 'var(--figma-color-bg-component)',
  componentHover: 'var(--figma-color-bg-component-hover)',
  componentPressed: 'var(--figma-color-bg-component-pressed)',
  componentSecondary: 'var(--figma-color-bg-component-secondary)',
  componentTertiary: 'var(--figma-color-bg-component-tertiary)',
  danger: 'var(--figma-color-bg-danger)',
  dangerHover: 'var(--figma-color-bg-danger-hover)',
  dangerPressed: 'var(--figma-color-bg-danger-pressed)',
  dangerSecondary: 'var(--figma-color-bg-danger-secondary)',
  dangerTertiary: 'var(--figma-color-bg-danger-tertiary)',
  disabled: 'var(--figma-color-bg-disabled)',
  disabledSecondary: 'var(--figma-color-bg-disabled-secondary)',
  hover: 'var(--figma-color-bg-hover)',
  inverse: 'var(--figma-color-bg-inverse)',
  onselected: 'var(--figma-color-bg-onselected)',
  onselectedHover: 'var(--figma-color-bg-onselected-hover)',
  onselectedPressed: 'var(--figma-color-bg-onselected-pressed)',
  pressed: 'var(--figma-color-bg-pressed)',
  secondary: 'var(--figma-color-bg-secondary)',
  selected: 'var(--figma-color-bg-selected)',
  selectedHover: 'var(--figma-color-bg-selected-hover)',
  selectedPressed: 'var(--figma-color-bg-selected-pressed)',
  selectedSecondary: 'var(--figma-color-bg-selected-secondary)',
  selectedStrong: 'var(--figma-color-bg-selected-strong)',
};

const borderFlat = {
  brand: 'var(--figma-color-border-brand)',
  brandHover: 'var(--figma-color-border-brand-hover)',
  brandPressed: 'var(--figma-color-border-brand-pressed)',
  brandSecondary: 'var(--figma-color-border-brand-secondary)',
  brandTertiary: 'var(--figma-color-border-brand-tertiary)',
  component: 'var(--figma-color-border-component)',
  componentHover: 'var(--figma-color-border-component-hover)',
  componentPressed: 'var(--figma-color-border-component-pressed)',
  componentSecondary: 'var(--figma-color-border-component-secondary)',
  componentTertiary: 'var(--figma-color-border-component-tertiary)',
  danger: 'var(--figma-color-border-danger)',
  dangerHover: 'var(--figma-color-border-danger-hover)',
  dangerPressed: 'var(--figma-color-border-danger-pressed)',
  dangerSecondary: 'var(--figma-color-border-danger-secondary)',
  dangerTertiary: 'var(--figma-color-border-danger-tertiary)',
  disabled: 'var(--figma-color-border-disabled)',
  disabledSecondary: 'var(--figma-color-border-disabled-secondary)',
  hover: 'var(--figma-color-border-hover)',
  inverse: 'var(--figma-color-border-inverse)',
  onselected: 'var(--figma-color-border-onselected)',
  onselectedHover: 'var(--figma-color-border-onselected-hover)',
  onselectedPressed: 'var(--figma-color-border-onselected-pressed)',
  pressed: 'var(--figma-color-border-pressed)',
  secondary: 'var(--figma-color-border-secondary)',
  selected: 'var(--figma-color-border-selected)',
  selectedHover: 'var(--figma-color-border-selected-hover)',
  selectedPressed: 'var(--figma-color-border-selected-pressed)',
  selectedSecondary: 'var(--figma-color-border-selected-secondary)',
  selectedStrong: 'var(--figma-color-border-selected-strong)',
};

const textFlat = {
  brand: 'var(--figma-color-text-brand)',
  brandHover: 'var(--figma-color-text-brand-hover)',
  brandPressed: 'var(--figma-color-text-brand-pressed)',
  brandSecondary: 'var(--figma-color-text-brand-secondary)',
  brandTertiary: 'var(--figma-color-text-brand-tertiary)',
  component: 'var(--figma-color-text-component)',
  componentHover: 'var(--figma-color-text-component-hover)',
  componentPressed: 'var(--figma-color-text-component-pressed)',
  componentSecondary: 'var(--figma-color-text-component-secondary)',
  componentTertiary: 'var(--figma-color-text-component-tertiary)',
  danger: 'var(--figma-color-text-danger)',
  dangerHover: 'var(--figma-color-text-danger-hover)',
  dangerPressed: 'var(--figma-color-text-danger-pressed)',
  dangerSecondary: 'var(--figma-color-text-danger-secondary)',
  dangerTertiary: 'var(--figma-color-text-danger-tertiary)',
  disabled: 'var(--figma-color-text-disabled)',
  disabledSecondary: 'var(--figma-color-text-disabled-secondary)',
  hover: 'var(--figma-color-text-hover)',
  inverse: 'var(--figma-color-text-inverse)',
  onselected: 'var(--figma-color-text-onselected)',
  onselectedHover: 'var(--figma-color-text-onselected-hover)',
  onselectedPressed: 'var(--figma-color-text-onselected-pressed)',
  pressed: 'var(--figma-color-text-pressed)',
  secondary: 'var(--figma-color-text-secondary)',
  selected: 'var(--figma-color-text-selected)',
  selectedHover: 'var(--figma-color-text-selected-hover)',
  selectedPressed: 'var(--figma-color-text-selected-pressed)',
  selectedSecondary: 'var(--figma-color-text-selected-secondary)',
  selectedStrong: 'var(--figma-color-text-selected-strong)',
};
const iconFlat = {
  brand: 'var(--figma-color-icon-brand)',
  brandHover: 'var(--figma-color-icon-brand-hover)',
  brandPressed: 'var(--figma-color-icon-brand-pressed)',
  brandSecondary: 'var(--figma-color-icon-brand-secondary)',
  brandTertiary: 'var(--figma-color-icon-brand-tertiary)',
  component: 'var(--figma-color-icon-component)',
  componentHover: 'var(--figma-color-icon-component-hover)',
  componentPressed: 'var(--figma-color-icon-component-pressed)',
  componentSecondary: 'var(--figma-color-icon-component-secondary)',
  componentTertiary: 'var(--figma-color-icon-component-tertiary)',
  danger: 'var(--figma-color-icon-danger)',
  dangerHover: 'var(--figma-color-icon-danger-hover)',
  dangerPressed: 'var(--figma-color-icon-danger-pressed)',
  dangerSecondary: 'var(--figma-color-icon-danger-secondary)',
  dangerTertiary: 'var(--figma-color-icon-danger-tertiary)',
  disabled: 'var(--figma-color-icon-disabled)',
  disabledSecondary: 'var(--figma-color-icon-disabled-secondary)',
  hover: 'var(--figma-color-icon-hover)',
  inverse: 'var(--figma-color-icon-inverse)',
  onselected: 'var(--figma-color-icon-onselected)',
  onselectedHover: 'var(--figma-color-icon-onselected-hover)',
  onselectedPressed: 'var(--figma-color-icon-onselected-pressed)',
  pressed: 'var(--figma-color-icon-pressed)',
  secondary: 'var(--figma-color-icon-secondary)',
  selected: 'var(--figma-color-icon-selected)',
  selectedHover: 'var(--figma-color-icon-selected-hover)',
  selectedPressed: 'var(--figma-color-icon-selected-pressed)',
  selectedSecondary: 'var(--figma-color-icon-selected-secondary)',
  selectedStrong: 'var(--figma-color-icon-selected-strong)',
};

export const colors = {
  fc: {
    bg: {
      DEFAULT: 'var(--figma-color-bg)',
      hover: 'var(--figma-color-bg-hover)',
      inverse: 'var(--figma-color-bg-inverse)',
      pressed: 'var(--figma-color-bg-pressed)',
      secondary: 'var(--figma-color-bg-secondary)',
      brand: {
        DEFAULT: 'var(--figma-color-bg-brand)',
        hover: 'var(--figma-color-bg-brand-hover)',
        pressed: 'var(--figma-color-bg-brand-pressed)',
        secondary: 'var(--figma-color-bg-brand-secondary)',
        tertiary: 'var(--figma-color-bg-brand-tertiary)',
      },
      component: {
        DEFAULT: 'var(--figma-color-bg-component)',
        hover: 'var(--figma-color-bg-component-hover)',
        pressed: 'var(--figma-color-bg-component-pressed)',
        secondary: 'var(--figma-color-bg-component-secondary)',
        tertiary: 'var(--figma-color-bg-component-tertiary)',
      },
      danger: {
        DEFAULT: 'var(--figma-color-bg-danger)',
        hover: 'var(--figma-color-bg-danger-hover)',
        pressed: 'var(--figma-color-bg-danger-pressed)',
        secondary: 'var(--figma-color-bg-danger-secondary)',
        tertiary: 'var(--figma-color-bg-danger-tertiary)',
      },
      disabled: {
        DEFAULT: 'var(--figma-color-bg-disabled)',
        secondary: 'var(--figma-color-bg-disabled-secondary)',
      },
      onselected: {
        DEFAULT: 'var(--figma-color-bg-onselected)',
        hover: 'var(--figma-color-bg-onselected-hover)',
        pressed: 'var(--figma-color-bg-onselected-pressed)',
      },
      selected: {
        DEFAULT: 'var(--figma-color-bg-selected)',
        hover: 'var(--figma-color-bg-selected-hover)',
        pressed: 'var(--figma-color-bg-selected-pressed)',
        secondary: 'var(--figma-color-bg-selected-secondary)',
        strong: 'var(--figma-color-bg-selected-strong)',
      },
    },
    border: {
      DEFAULT: 'var(--figma-color-border)',
      hover: 'var(--figma-color-border-hover)',
      inverse: 'var(--figma-color-border-inverse)',
      pressed: 'var(--figma-color-border-pressed)',
      secondary: 'var(--figma-color-border-secondary)',
      brand: {
        DEFAULT: 'var(--figma-color-border-brand)',
        hover: 'var(--figma-color-border-brand-hover)',
        pressed: 'var(--figma-color-border-brand-pressed)',
        secondary: 'var(--figma-color-border-brand-secondary)',
        tertiary: 'var(--figma-color-border-brand-tertiary)',
      },
      component: {
        DEFAULT: 'var(--figma-color-border-component)',
        hover: 'var(--figma-color-border-component-hover)',
        pressed: 'var(--figma-color-border-component-pressed)',
        secondary: 'var(--figma-color-border-component-secondary)',
        tertiary: 'var(--figma-color-border-component-tertiary)',
      },
      danger: {
        DEFAULT: 'var(--figma-color-border-danger)',
        hover: 'var(--figma-color-border-danger-hover)',
        pressed: 'var(--figma-color-border-danger-pressed)',
        secondary: 'var(--figma-color-border-danger-secondary)',
        tertiary: 'var(--figma-color-border-danger-tertiary)',
      },
      disabled: {
        DEFAULT: 'var(--figma-color-border-disabled)',
        secondary: 'var(--figma-color-border-disabled-secondary)',
      },
      onselected: {
        DEFAULT: 'var(--figma-color-border-onselected)',
        hover: 'var(--figma-color-border-onselected-hover)',
        pressed: 'var(--figma-color-border-onselected-pressed)',
      },
      selected: {
        DEFAULT: 'var(--figma-color-border-selected)',
        hover: 'var(--figma-color-border-selected-hover)',
        pressed: 'var(--figma-color-border-selected-pressed)',
        secondary: 'var(--figma-color-border-selected-secondary)',
        strong: 'var(--figma-color-border-selected-strong)',
      },
    },
    text: {
      DEFAULT: 'var(--figma-color-text)',
      hover: 'var(--figma-color-text-hover)',
      inverse: 'var(--figma-color-text-inverse)',
      pressed: 'var(--figma-color-text-pressed)',
      secondary: 'var(--figma-color-text-secondary)',
      brand: {
        DEFAULT: 'var(--figma-color-text-brand)',
        hover: 'var(--figma-color-text-brand-hover)',
        pressed: 'var(--figma-color-text-brand-pressed)',
        secondary: 'var(--figma-color-text-brand-secondary)',
        tertiary: 'var(--figma-color-text-brand-tertiary)',
      },
      component: {
        DEFAULT: 'var(--figma-color-text-component)',
        hover: 'var(--figma-color-text-component-hover)',
        pressed: 'var(--figma-color-text-component-pressed)',
        secondary: 'var(--figma-color-text-component-secondary)',
        tertiary: 'var(--figma-color-text-component-tertiary)',
      },
      danger: {
        DEFAULT: 'var(--figma-color-text-danger)',
        hover: 'var(--figma-color-text-danger-hover)',
        pressed: 'var(--figma-color-text-danger-pressed)',
        secondary: 'var(--figma-color-text-danger-secondary)',
        tertiary: 'var(--figma-color-text-danger-tertiary)',
      },
      disabled: {
        DEFAULT: 'var(--figma-color-text-disabled)',
        secondary: 'var(--figma-color-text-disabled-secondary)',
      },
      onselected: {
        DEFAULT: 'var(--figma-color-text-onselected)',
        hover: 'var(--figma-color-text-onselected-hover)',
        pressed: 'var(--figma-color-text-onselected-pressed)',
      },
      selected: {
        DEFAULT: 'var(--figma-color-text-selected)',
        hover: 'var(--figma-color-text-selected-hover)',
        pressed: 'var(--figma-color-text-selected-pressed)',
        secondary: 'var(--figma-color-text-selected-secondary)',
        strong: 'var(--figma-color-text-selected-strong)',
      },
    },
    icon: {
      DEFAULT: 'var(--figma-color-icon)',
      hover: 'var(--figma-color-icon-hover)',
      inverse: 'var(--figma-color-icon-inverse)',
      pressed: 'var(--figma-color-icon-pressed)',
      secondary: 'var(--figma-color-icon-secondary)',
      brand: {
        DEFAULT: 'var(--figma-color-icon-brand)',
        hover: 'var(--figma-color-icon-brand-hover)',
        pressed: 'var(--figma-color-icon-brand-pressed)',
        secondary: 'var(--figma-color-icon-brand-secondary)',
        tertiary: 'var(--figma-color-icon-brand-tertiary)',
      },
      component: {
        DEFAULT: 'var(--figma-color-icon-component)',
        hover: 'var(--figma-color-icon-component-hover)',
        pressed: 'var(--figma-color-icon-component-pressed)',
        secondary: 'var(--figma-color-icon-component-secondary)',
        tertiary: 'var(--figma-color-icon-component-tertiary)',
      },
      danger: {
        DEFAULT: 'var(--figma-color-icon-danger)',
        hover: 'var(--figma-color-icon-danger-hover)',
        pressed: 'var(--figma-color-icon-danger-pressed)',
        secondary: 'var(--figma-color-icon-danger-secondary)',
        tertiary: 'var(--figma-color-icon-danger-tertiary)',
      },
      disabled: {
        DEFAULT: 'var(--figma-color-icon-disabled)',
        secondary: 'var(--figma-color-icon-disabled-secondary)',
      },
      onselected: {
        DEFAULT: 'var(--figma-color-icon-onselected)',
        hover: 'var(--figma-color-icon-onselected-hover)',
        pressed: 'var(--figma-color-icon-onselected-pressed)',
      },
      selected: {
        DEFAULT: 'var(--figma-color-icon-selected)',
        hover: 'var(--figma-color-icon-selected-hover)',
        pressed: 'var(--figma-color-icon-selected-pressed)',
        secondary: 'var(--figma-color-icon-selected-secondary)',
        strong: 'var(--figma-color-icon-selected-strong)',
      },
    },
  },

  // 'fc-bg': 'var(--figma-color-bg-brand)',
  // 'fc-bg-brand': 'var(--figma-color-bg-brand)',
  // 'fc-bg-brand-hover': 'var(--figma-color-bg-brand-hover)',
  // 'fc-bg-brand-pressed': 'var(--figma-color-bg-brand-pressed)',
  // 'fc-bg-brand-secondary': 'var(--figma-color-bg-brand-secondary)',
  // 'fc-bg-brand-tertiary': 'var(--figma-color-bg-brand-tertiary)',
  // 'fc-bg-component': 'var(--figma-color-bg-component)',
  // 'fc-bg-component-hover': 'var(--figma-color-bg-component-hover)',
  // 'fc-bg-component-pressed': 'var(--figma-color-bg-component-pressed)',
  // 'fc-bg-component-secondary': 'var(--figma-color-bg-component-secondary)',
  // 'fc-bg-component-tertiary': 'var(--figma-color-bg-component-tertiary)',
  // 'fc-bg-danger': 'var(--figma-color-bg-danger)',
  // 'fc-bg-danger-hover': 'var(--figma-color-bg-danger-hover)',
  // 'fc-bg-danger-pressed': 'var(--figma-color-bg-danger-pressed)',
  // 'fc-bg-danger-secondary': 'var(--figma-color-bg-danger-secondary)',
  // 'fc-bg-danger-tertiary': 'var(--figma-color-bg-danger-tertiary)',
  // 'fc-bg-disabled': 'var(--figma-color-bg-disabled)',
  // 'fc-bg-disabled-secondary': 'var(--figma-color-bg-disabled-secondary)',
  // 'fc-bg-hover': 'var(--figma-color-bg-hover)',
  // 'fc-bg-inverse': 'var(--figma-color-bg-inverse)',
  // 'fc-bg-onselected': 'var(--figma-color-bg-onselected)',
  // 'fc-bg-onselected-hover': 'var(--figma-color-bg-onselected-hover)',
  // 'fc-bg-onselected-pressed': 'var(--figma-color-bg-onselected-pressed)',
  // 'fc-bg-pressed': 'var(--figma-color-bg-pressed)',
  // 'fc-bg-secondary': 'var(--figma-color-bg-secondary)',
  // 'fc-bg-selected': 'var(--figma-color-bg-selected)',
  // 'fc-bg-selected-hover': 'var(--figma-color-bg-selected-hover)',
  // 'fc-bg-selected-pressed': 'var(--figma-color-bg-selected-pressed)',
  // 'fc-bg-selected-secondary': 'var(--figma-color-bg-selected-secondary)',
  // 'fc-bg-selected-strong': 'var(--figma-color-bg-selected-strong)',
  // 'fc-bg-selected-tertiary': 'var(--figma-color-bg-selected-tertiary)',
  // 'fc-bg-success': 'var(--figma-color-bg-success)',
  // 'fc-bg-success-hover': 'var(--figma-color-bg-success-hover)',
  // 'fc-bg-success-pressed': 'var(--figma-color-bg-success-pressed)',
  // 'fc-bg-success-secondary': 'var(--figma-color-bg-success-secondary)',
  // 'fc-bg-success-tertiary': 'var(--figma-color-bg-success-tertiary)',
  // 'fc-bg-tertiary': 'var(--figma-color-bg-tertiary)',
  // 'fc-bg-warning': 'var(--figma-color-bg-warning)',
  // 'fc-bg-warning-hover': 'var(--figma-color-bg-warning-hover)',
  // 'fc-bg-warning-pressed': 'var(--figma-color-bg-warning-pressed)',
  // 'fc-bg-warning-secondary': 'var(--figma-color-bg-warning-secondary)',
  // 'fc-bg-warning-tertiary': 'var(--figma-color-bg-warning-tertiary)',
  // 'fc-border': 'var(--figma-color-border)',
  // 'fc-border-brand': 'var(--figma-color-border-brand)',
  // 'fc-border-brand-strong': 'var(--figma-color-border-brand-strong)',
  // 'fc-border-component': 'var(--figma-color-border-component)',
  // 'fc-border-component-hover': 'var(--figma-color-border-component-hover)',
  // 'fc-border-component-strong': 'var(--figma-color-border-component-strong)',
  // 'fc-border-danger': 'var(--figma-color-border-danger)',
  // 'fc-border-danger-strong': 'var(--figma-color-border-danger-strong)',
  // 'fc-border-disabled': 'var(--figma-color-border-disabled)',
  // 'fc-border-disabled-strong': 'var(--figma-color-border-disabled-strong)',
  // 'fc-border-onbrand': 'var(--figma-color-border-onbrand)',
  // 'fc-border-onbrand-strong': 'var(--figma-color-border-onbrand-strong)',
  // 'fc-border-oncomponent': 'var(--figma-color-border-oncomponent)',
  // 'fc-border-oncomponent-strong': 'var(--figma-color-border-oncomponent-strong)',
  // 'fc-border-ondanger': 'var(--figma-color-border-ondanger)',
  // 'fc-border-ondanger-strong': 'var(--figma-color-border-ondanger-strong)',
  // 'fc-border-onselected': 'var(--figma-color-border-onselected)',
  // 'fc-border-onselected-strong': 'var(--figma-color-border-onselected-strong)',
  // 'fc-border-onsuccess': 'var(--figma-color-border-onsuccess)',
  // 'fc-border-onsuccess-strong': 'var(--figma-color-border-onsuccess-strong)',
  // 'fc-border-onwarning': 'var(--figma-color-border-onwarning)',
  // 'fc-border-onwarning-strong': 'var(--figma-color-border-onwarning-strong)',
  // 'fc-border-selected': 'var(--figma-color-border-selected)',
  // 'fc-border-selected-strong': 'var(--figma-color-border-selected-strong)',
  // 'fc-border-strong': 'var(--figma-color-border-strong)',
  // 'fc-border-success': 'var(--figma-color-border-success)',
  // 'fc-border-success-strong': 'var(--figma-color-border-success-strong)',
  // 'fc-border-warning': 'var(--figma-color-border-warning)',
  // 'fc-border-warning-strong': 'var(--figma-color-border-warning-strong)',
  // 'fc-icon': 'var(--figma-color-icon)',
  // 'fc-icon-brand': 'var(--figma-color-icon-brand)',
  // 'fc-icon-brand-pressed': 'var(--figma-color-icon-brand-pressed)',
  // 'fc-icon-brand-secondary': 'var(--figma-color-icon-brand-secondary)',
  // 'fc-icon-brand-tertiary': 'var(--figma-color-icon-brand-tertiary)',
  // 'fc-icon-component': 'var(--figma-color-icon-component)',
  // 'fc-icon-component-pressed': 'var(--figma-color-icon-component-pressed)',
  // 'fc-icon-component-secondary': 'var(--figma-color-icon-component-secondary)',
  // 'fc-icon-component-tertiary': 'var(--figma-color-icon-component-tertiary)',
  // 'fc-icon-danger': 'var(--figma-color-icon-danger)',
  // 'fc-icon-danger-hover': 'var(--figma-color-icon-danger-hover)',
  // 'fc-icon-danger-pressed': 'var(--figma-color-icon-danger-pressed)',
  // 'fc-icon-danger-secondary': 'var(--figma-color-icon-danger-secondary)',
  // 'fc-icon-danger-secondary-hover': 'var(--figma-color-icon-danger-secondary-hover)',
  // 'fc-icon-danger-tertiary': 'var(--figma-color-icon-danger-tertiary)',
  // 'fc-icon-disabled': 'var(--figma-color-icon-disabled)',
  // 'fc-icon-hover': 'var(--figma-color-icon-hover)',
  // 'fc-icon-onbrand': 'var(--figma-color-icon-onbrand)',
  // 'fc-icon-onbrand-secondary': 'var(--figma-color-icon-onbrand-secondary)',
  // 'fc-icon-onbrand-tertiary': 'var(--figma-color-icon-onbrand-tertiary)',
  // 'fc-icon-oncomponent': 'var(--figma-color-icon-oncomponent)',
  // 'fc-icon-oncomponent-secondary': 'var(--figma-color-icon-oncomponent-secondary)',
  // 'fc-icon-oncomponent-tertiary': 'var(--figma-color-icon-oncomponent-tertiary)',
  // 'fc-icon-ondanger': 'var(--figma-color-icon-ondanger)',
  // 'fc-icon-ondanger-secondary': 'var(--figma-color-icon-ondanger-secondary)',
  // 'fc-icon-ondanger-tertiary': 'var(--figma-color-icon-ondanger-tertiary)',
  // 'fc-icon-ondisabled': 'var(--figma-color-icon-ondisabled)',
  // 'fc-icon-oninverse': 'var(--figma-color-icon-oninverse)',
  // 'fc-icon-onselected': 'var(--figma-color-icon-onselected)',
  // 'fc-icon-onselected-secondary': 'var(--figma-color-icon-onselected-secondary)',
  // 'fc-icon-onselected-strong': 'var(--figma-color-icon-onselected-strong)',
  // 'fc-icon-onselected-tertiary': 'var(--figma-color-icon-onselected-tertiary)',
  // 'fc-icon-onsuccess': 'var(--figma-color-icon-onsuccess)',
  // 'fc-icon-onsuccess-secondary': 'var(--figma-color-icon-onsuccess-secondary)',
  // 'fc-icon-onsuccess-tertiary': 'var(--figma-color-icon-onsuccess-tertiary)',
  // 'fc-icon-onwarning': 'var(--figma-color-icon-onwarning)',
  // 'fc-icon-onwarning-secondary': 'var(--figma-color-icon-onwarning-secondary)',
  // 'fc-icon-onwarning-tertiary': 'var(--figma-color-icon-onwarning-tertiary)',
  // 'fc-icon-pressed': 'var(--figma-color-icon-pressed)',
  // 'fc-icon-secondary': 'var(--figma-color-icon-secondary)',
  // 'fc-icon-secondary-hover': 'var(--figma-color-icon-secondary-hover)',
  // 'fc-icon-selected': 'var(--figma-color-icon-selected)',
  // 'fc-icon-selected-secondary': 'var(--figma-color-icon-selected-secondary)',
  // 'fc-icon-selected-tertiary': 'var(--figma-color-icon-selected-tertiary)',
  // 'fc-icon-success': 'var(--figma-color-icon-success)',
  // 'fc-icon-success-pressed': 'var(--figma-color-icon-success-pressed)',
  // 'fc-icon-success-secondary': 'var(--figma-color-icon-success-secondary)',
  // 'fc-icon-success-tertiary': 'var(--figma-color-icon-success-tertiary)',
  // 'fc-icon-tertiary': 'var(--figma-color-icon-tertiary)',
  // 'fc-icon-tertiary-hover': 'var(--figma-color-icon-tertiary-hover)',
  // 'fc-icon-warning': 'var(--figma-color-icon-warning)',
  // 'fc-icon-warning-pressed': 'var(--figma-color-icon-warning-pressed)',
  // 'fc-icon-warning-secondary': 'var(--figma-color-icon-warning-secondary)',
  // 'fc-icon-warning-tertiary': 'var(--figma-color-icon-warning-tertiary)',
  // 'fc-text': 'var(--figma-color-text)',
  // 'fc-text-brand': 'var(--figma-color-text-brand)',
  // 'fc-text-brand-secondary': 'var(--figma-color-text-brand-secondary)',
  // 'fc-text-brand-tertiary': 'var(--figma-color-text-brand-tertiary)',
  // 'fc-text-component': 'var(--figma-color-text-component)',
  // 'fc-text-component-pressed': 'var(--figma-color-text-component-pressed)',
  // 'fc-text-component-secondary': 'var(--figma-color-text-component-secondary)',
  // 'fc-text-component-tertiary': 'var(--figma-color-text-component-tertiary)',
  // 'fc-text-danger': 'var(--figma-color-text-danger)',
  // 'fc-text-danger-secondary': 'var(--figma-color-text-danger-secondary)',
  // 'fc-text-danger-tertiary': 'var(--figma-color-text-danger-tertiary)',
  // 'fc-text-disabled': 'var(--figma-color-text-disabled)',
  // 'fc-text-hover': 'var(--figma-color-text-hover)',
  // 'fc-text-onbrand': 'var(--figma-color-text-onbrand)',
  // 'fc-text-onbrand-secondary': 'var(--figma-color-text-onbrand-secondary)',
  // 'fc-text-onbrand-tertiary': 'var(--figma-color-text-onbrand-tertiary)',
  // 'fc-text-oncomponent': 'var(--figma-color-text-oncomponent)',
  // 'fc-text-oncomponent-secondary': 'var(--figma-color-text-oncomponent-secondary)',
  // 'fc-text-oncomponent-tertiary': 'var(--figma-color-text-oncomponent-tertiary)',
  // 'fc-text-ondanger': 'var(--figma-color-text-ondanger)',
  // 'fc-text-ondanger-secondary': 'var(--figma-color-text-ondanger-secondary)',
  // 'fc-text-ondanger-tertiary': 'var(--figma-color-text-ondanger-tertiary)',
  // 'fc-text-ondisabled': 'var(--figma-color-text-ondisabled)',
  // 'fc-text-oninverse': 'var(--figma-color-text-oninverse)',
  // 'fc-text-onselected': 'var(--figma-color-text-onselected)',
  // 'fc-text-onselected-secondary': 'var(--figma-color-text-onselected-secondary)',
  // 'fc-text-onselected-strong': 'var(--figma-color-text-onselected-strong)',
  // 'fc-text-onselected-tertiary': 'var(--figma-color-text-onselected-tertiary)',
  // 'fc-text-onsuccess': 'var(--figma-color-text-onsuccess)',
  // 'fc-text-onsuccess-secondary': 'var(--figma-color-text-onsuccess-secondary)',
  // 'fc-text-onsuccess-tertiary': 'var(--figma-color-text-onsuccess-tertiary)',
  // 'fc-text-onwarning': 'var(--figma-color-text-onwarning)',
  // 'fc-text-onwarning-secondary': 'var(--figma-color-text-onwarning-secondary)',
  // 'fc-text-onwarning-tertiary': 'var(--figma-color-text-onwarning-tertiary)',
  // 'fc-text-secondary': 'var(--figma-color-text-secondary)',
  // 'fc-text-secondary-hover': 'var(--figma-color-text-secondary-hover)',
  // 'fc-text-selected': 'var(--figma-color-text-selected)',
  // 'fc-text-selected-secondary': 'var(--figma-color-text-selected-secondary)',
  // 'fc-text-selected-tertiary': 'var(--figma-color-text-selected-tertiary)',
  // 'fc-text-success': 'var(--figma-color-text-success)',
  // 'fc-text-success-secondary': 'var(--figma-color-text-success-secondary)',
  // 'fc-text-success-tertiary': 'var(--figma-color-text-success-tertiary)',
  // 'fc-text-tertiary': 'var(--figma-color-text-tertiary)',
  // 'fc-text-tertiary-hover': 'var(--figma-color-text-tertiary-hover)',
  // 'fc-text-warning': 'var(--figma-color-text-warning)',
  // 'fc-text-warning-secondary': 'var(--figma-color-text-warning-secondary)',
  // 'fc-text-warning-tertiary': 'var(--figma-color-text-warning-tertiary)',
};
export const theme = {
  colors,
};
