/* This file is generated automatically by Design Sync. Do not edit this file directly. */

import { css } from "styled-components";

export const largeRegularXs = css`
  font-family: Kode Mono;
  font-size: 1.125rem;
  font-weight: 400;
  line-height: 1.25rem;
  letter-spacing: 0px;
`;

export const largeRegularSm = css`
  font-family: Kode Mono;
  font-size: 1.125rem;
  font-weight: 400;
  line-height: 1.25rem;
  letter-spacing: 0px;
`;

export const largeRegularMd = css`
  font-family: Kode Mono;
  font-size: 1.125rem;
  font-weight: 400;
  line-height: 1.25rem;
  letter-spacing: 0px;
`;

export const largeRegularLg = css`
  font-family: Kode Mono;
  font-size: 1.25rem;
  font-weight: 400;
  line-height: 1.5rem;
  letter-spacing: 0px;
`;

export const largeRegularXl = css`
  font-family: Kode Mono;
  font-size: 1.25rem;
  font-weight: 400;
  line-height: 1.5rem;
  letter-spacing: 0px;
`;

export const largeRegularXxl = css`
  font-family: Kode Mono;
  font-size: 1.25rem;
  font-weight: 400;
  line-height: 1.5rem;
  letter-spacing: 0px;
`;

export const largeBoldXs = css`
  font-family: Kode Mono;
  font-size: 1.125rem;
  font-weight: 500;
  line-height: 1.25rem;
  letter-spacing: 0px;
`;

export const largeBoldSm = css`
  font-family: Kode Mono;
  font-size: 1.125rem;
  font-weight: 500;
  line-height: 1.25rem;
  letter-spacing: 0px;
`;

export const largeBoldMd = css`
  font-family: Kode Mono;
  font-size: 1.125rem;
  font-weight: 500;
  line-height: 1.25rem;
  letter-spacing: 0px;
`;

export const largeBoldLg = css`
  font-family: Kode Mono;
  font-size: 1.25rem;
  font-weight: 500;
  line-height: 1.5rem;
  letter-spacing: 0px;
`;

export const largeBoldXl = css`
  font-family: Kode Mono;
  font-size: 1.25rem;
  font-weight: 500;
  line-height: 1.5rem;
  letter-spacing: 0px;
`;

export const largeBoldXxl = css`
  font-family: Kode Mono;
  font-size: 1.25rem;
  font-weight: 500;
  line-height: 1.5rem;
  letter-spacing: 0px;
`;

export const smallRegularXs = css`
  font-family: Kode Mono;
  font-size: 0.75rem;
  font-weight: 400;
  line-height: 1rem;
  letter-spacing: 0px;
`;

export const smallRegularSm = css`
  font-family: Kode Mono;
  font-size: 0.75rem;
  font-weight: 400;
  line-height: 1rem;
  letter-spacing: 0px;
`;

export const smallRegularMd = css`
  font-family: Kode Mono;
  font-size: 0.75rem;
  font-weight: 400;
  line-height: 1rem;
  letter-spacing: 0px;
`;

export const smallRegularLg = css`
  font-family: Kode Mono;
  font-size: 0.875rem;
  font-weight: 400;
  line-height: 1rem;
  letter-spacing: 0px;
`;

export const smallRegularXl = css`
  font-family: Kode Mono;
  font-size: 0.875rem;
  font-weight: 400;
  line-height: 1rem;
  letter-spacing: 0px;
`;

export const smallRegularXxl = css`
  font-family: Kode Mono;
  font-size: 0.875rem;
  font-weight: 400;
  line-height: 1rem;
  letter-spacing: 0px;
`;

export const smallBoldXs = css`
  font-family: Kode Mono;
  font-size: 0.75rem;
  font-weight: 700;
  line-height: 1rem;
  letter-spacing: 0px;
`;

export const smallBoldSm = css`
  font-family: Kode Mono;
  font-size: 0.75rem;
  font-weight: 700;
  line-height: 1rem;
  letter-spacing: 0px;
`;

export const smallBoldMd = css`
  font-family: Kode Mono;
  font-size: 0.75rem;
  font-weight: 700;
  line-height: 1rem;
  letter-spacing: 0px;
`;

export const smallBoldLg = css`
  font-family: Kode Mono;
  font-size: 0.875rem;
  font-weight: 700;
  line-height: 1rem;
  letter-spacing: 0px;
`;

export const smallBoldXl = css`
  font-family: Kode Mono;
  font-size: 0.875rem;
  font-weight: 700;
  line-height: 1rem;
  letter-spacing: 0px;
`;

export const smallBoldXxl = css`
  font-family: Kode Mono;
  font-size: 0.875rem;
  font-weight: 700;
  line-height: 1rem;
  letter-spacing: 0px;
`;

export const smallestRegularXs = css`
  font-family: Kode Mono;
  font-size: 0.6875rem;
  font-weight: 400;
  line-height: 0.875rem;
  letter-spacing: 0px;
`;

export const smallestRegularSm = css`
  font-family: Kode Mono;
  font-size: 0.6875rem;
  font-weight: 400;
  line-height: 0.875rem;
  letter-spacing: 0px;
`;

export const smallestRegularMd = css`
  font-family: Kode Mono;
  font-size: 0.6875rem;
  font-weight: 400;
  line-height: 0.875rem;
  letter-spacing: 0px;
`;

export const smallestRegularLg = css`
  font-family: Kode Mono;
  font-size: 0.75rem;
  font-weight: 400;
  line-height: 1rem;
  letter-spacing: 0px;
`;

export const smallestRegularXl = css`
  font-family: Kode Mono;
  font-size: 0.75rem;
  font-weight: 400;
  line-height: 1rem;
  letter-spacing: 0px;
`;

export const smallestRegularXxl = css`
  font-family: Kode Mono;
  font-size: 0.75rem;
  font-weight: 400;
  line-height: 1rem;
  letter-spacing: 0px;
`;

export const smallestBoldXs = css`
  font-family: Kode Mono;
  font-size: 0.6875rem;
  font-weight: 700;
  line-height: 0.875rem;
  letter-spacing: 0px;
`;

export const smallestBoldSm = css`
  font-family: Kode Mono;
  font-size: 0.6875rem;
  font-weight: 700;
  line-height: 0.875rem;
  letter-spacing: 0px;
`;

export const smallestBoldMd = css`
  font-family: Kode Mono;
  font-size: 0.6875rem;
  font-weight: 700;
  line-height: 0.875rem;
  letter-spacing: 0px;
`;

export const smallestBoldLg = css`
  font-family: Kode Mono;
  font-size: 0.75rem;
  font-weight: 700;
  line-height: 1rem;
  letter-spacing: 0px;
`;

export const smallestBoldXl = css`
  font-family: Kode Mono;
  font-size: 0.75rem;
  font-weight: 700;
  line-height: 1rem;
  letter-spacing: 0px;
`;

export const smallestBoldXxl = css`
  font-family: Kode Mono;
  font-size: 0.75rem;
  font-weight: 700;
  line-height: 1rem;
  letter-spacing: 0px;
`;

export const baseRegularXs = css`
  font-family: Kode Mono;
  font-size: 0.875rem;
  font-weight: 400;
  line-height: 1.125rem;
  letter-spacing: 0px;
`;

export const baseRegularSm = css`
  font-family: Kode Mono;
  font-size: 0.875rem;
  font-weight: 400;
  line-height: 1.125rem;
  letter-spacing: 0px;
`;

export const baseRegularMd = css`
  font-family: Kode Mono;
  font-size: 0.875rem;
  font-weight: 400;
  line-height: 1.125rem;
  letter-spacing: 0px;
`;

export const baseRegularLg = css`
  font-family: Kode Mono;
  font-size: 1rem;
  font-weight: 400;
  line-height: 1.25rem;
  letter-spacing: 0px;
`;

export const baseRegularXl = css`
  font-family: Kode Mono;
  font-size: 1rem;
  font-weight: 400;
  line-height: 1.25rem;
  letter-spacing: 0px;
`;

export const baseRegularXxl = css`
  font-family: Kode Mono;
  font-size: 1rem;
  font-weight: 400;
  line-height: 1.25rem;
  letter-spacing: 0px;
`;

export const baseBoldXs = css`
  font-family: Kode Mono;
  font-size: 0.875rem;
  font-weight: 700;
  line-height: 1.125rem;
  letter-spacing: 0px;
`;

export const baseBoldSm = css`
  font-family: Kode Mono;
  font-size: 0.875rem;
  font-weight: 700;
  line-height: 1.125rem;
  letter-spacing: 0px;
`;

export const baseBoldMd = css`
  font-family: Kode Mono;
  font-size: 0.875rem;
  font-weight: 700;
  line-height: 1.125rem;
  letter-spacing: 0px;
`;

export const baseBoldLg = css`
  font-family: Kode Mono;
  font-size: 1rem;
  font-weight: 700;
  line-height: 1.25rem;
  letter-spacing: 0px;
`;

export const baseBoldXl = css`
  font-family: Kode Mono;
  font-size: 1rem;
  font-weight: 700;
  line-height: 1.25rem;
  letter-spacing: 0px;
`;

export const baseBoldXxl = css`
  font-family: Kode Mono;
  font-size: 1rem;
  font-weight: 700;
  line-height: 1.25rem;
  letter-spacing: 0px;
`;

export const fontH1Xs = css`
  font-family: Inter;
  font-size: 2rem;
  font-weight: 500;
  line-height: 2.25rem;
  letter-spacing: 0px;
`;

export const fontH1Sm = css`
  font-family: Inter;
  font-size: 2rem;
  font-weight: 500;
  line-height: 2.25rem;
  letter-spacing: 0px;
`;

export const fontH1Md = css`
  font-family: Inter;
  font-size: 2rem;
  font-weight: 500;
  line-height: 2.25rem;
  letter-spacing: 0px;
`;

export const fontH1Lg = css`
  font-family: Inter;
  font-size: 2.5rem;
  font-weight: 500;
  line-height: 3rem;
  letter-spacing: 0px;
`;

export const fontH1Xl = css`
  font-family: Inter;
  font-size: 2.5rem;
  font-weight: 500;
  line-height: 3rem;
  letter-spacing: 0px;
`;

export const fontH1Xxl = css`
  font-family: Inter;
  font-size: 2.5rem;
  font-weight: 500;
  line-height: 3rem;
  letter-spacing: 0px;
`;

export const fontH2Xs = css`
  font-family: Inter;
  font-size: 1.75rem;
  font-weight: 500;
  line-height: 2rem;
  letter-spacing: 0px;
`;

export const fontH2Sm = css`
  font-family: Inter;
  font-size: 1.75rem;
  font-weight: 500;
  line-height: 2rem;
  letter-spacing: 0px;
`;

export const fontH2Md = css`
  font-family: Inter;
  font-size: 1.75rem;
  font-weight: 500;
  line-height: 2rem;
  letter-spacing: 0px;
`;

export const fontH2Lg = css`
  font-family: Inter;
  font-size: 2rem;
  font-weight: 500;
  line-height: 2.25rem;
  letter-spacing: 0px;
`;

export const fontH2Xl = css`
  font-family: Inter;
  font-size: 2rem;
  font-weight: 500;
  line-height: 2.25rem;
  letter-spacing: 0px;
`;

export const fontH2Xxl = css`
  font-family: Inter;
  font-size: 2rem;
  font-weight: 500;
  line-height: 2.25rem;
  letter-spacing: 0px;
`;

export const fontH3Xs = css`
  font-family: Inter;
  font-size: 1.5rem;
  font-weight: 500;
  line-height: 1.75rem;
  letter-spacing: 0px;
`;

export const fontH3Sm = css`
  font-family: Inter;
  font-size: 1.5rem;
  font-weight: 500;
  line-height: 1.75rem;
  letter-spacing: 0px;
`;

export const fontH3Md = css`
  font-family: Inter;
  font-size: 1.5rem;
  font-weight: 500;
  line-height: 1.75rem;
  letter-spacing: 0px;
`;

export const fontH3Lg = css`
  font-family: Inter;
  font-size: 1.75rem;
  font-weight: 500;
  line-height: 2rem;
  letter-spacing: 0px;
`;

export const fontH3Xl = css`
  font-family: Inter;
  font-size: 1.75rem;
  font-weight: 500;
  line-height: 2rem;
  letter-spacing: 0px;
`;

export const fontH3Xxl = css`
  font-family: Inter;
  font-size: 1.75rem;
  font-weight: 500;
  line-height: 2rem;
  letter-spacing: 0px;
`;

export const fontH4Xs = css`
  font-family: Inter;
  font-size: 1.25rem;
  font-weight: 500;
  line-height: 1.5rem;
  letter-spacing: 0px;
`;

export const fontH4Sm = css`
  font-family: Inter;
  font-size: 1.25rem;
  font-weight: 500;
  line-height: 1.5rem;
  letter-spacing: 0px;
`;

export const fontH4Md = css`
  font-family: Inter;
  font-size: 1.25rem;
  font-weight: 500;
  line-height: 1.5rem;
  letter-spacing: 0px;
`;

export const fontH4Lg = css`
  font-family: Inter;
  font-size: 1.5rem;
  font-weight: 500;
  line-height: 1.75rem;
  letter-spacing: 0px;
`;

export const fontH4Xl = css`
  font-family: Inter;
  font-size: 1.5rem;
  font-weight: 500;
  line-height: 1.75rem;
  letter-spacing: 0px;
`;

export const fontH4Xxl = css`
  font-family: Inter;
  font-size: 1.5rem;
  font-weight: 500;
  line-height: 1.75rem;
  letter-spacing: 0px;
`;

export const fontH5Xs = css`
  font-family: Inter;
  font-size: 1rem;
  font-weight: 500;
  line-height: 1.25rem;
  letter-spacing: 0px;
`;

export const fontH5Sm = css`
  font-family: Inter;
  font-size: 1rem;
  font-weight: 500;
  line-height: 1.25rem;
  letter-spacing: 0px;
`;

export const fontH5Md = css`
  font-family: Inter;
  font-size: 1rem;
  font-weight: 500;
  line-height: 1.25rem;
  letter-spacing: 0px;
`;

export const fontH5Lg = css`
  font-family: Inter;
  font-size: 1.25rem;
  font-weight: 500;
  line-height: 1.5rem;
  letter-spacing: 0px;
`;

export const fontH5Xl = css`
  font-family: Inter;
  font-size: 1.25rem;
  font-weight: 500;
  line-height: 1.5rem;
  letter-spacing: 0px;
`;

export const fontH5Xxl = css`
  font-family: Inter;
  font-size: 1.25rem;
  font-weight: 500;
  line-height: 1.5rem;
  letter-spacing: 0px;
`;

export const fontH6Xs = css`
  font-family: Inter;
  font-size: 0.875rem;
  font-weight: 500;
  line-height: 1.125rem;
  letter-spacing: 0px;
`;

export const fontH6Sm = css`
  font-family: Inter;
  font-size: 0.875rem;
  font-weight: 500;
  line-height: 1.125rem;
  letter-spacing: 0px;
`;

export const fontH6Md = css`
  font-family: Inter;
  font-size: 0.875rem;
  font-weight: 500;
  line-height: 1.125rem;
  letter-spacing: 0px;
`;

export const fontH6Lg = css`
  font-family: Inter;
  font-size: 1rem;
  font-weight: 500;
  line-height: 1.25rem;
  letter-spacing: 0px;
`;

export const fontH6Xl = css`
  font-family: Inter;
  font-size: 1rem;
  font-weight: 500;
  line-height: 1.25rem;
  letter-spacing: 0px;
`;

export const fontH6Xxl = css`
  font-family: Inter;
  font-size: 1rem;
  font-weight: 500;
  line-height: 1.25rem;
  letter-spacing: 0px;
`;

export const baseRegularXs = css`
  font-family: Kode Mono;
  font-size: 0.75rem;
  font-weight: 400;
  line-height: 1rem;
  letter-spacing: 0px;
`;

export const baseRegularSm = css`
  font-family: Kode Mono;
  font-size: 0.875rem;
  font-weight: 400;
  line-height: 1.125rem;
  letter-spacing: 0px;
`;

export const baseRegularMd = css`
  font-family: Kode Mono;
  font-size: 1rem;
  font-weight: 400;
  line-height: 1.25rem;
  letter-spacing: 0px;
`;

export const baseRegularLg = css`
  font-family: Kode Mono;
  font-size: 1rem;
  font-weight: 400;
  line-height: 1.25rem;
  letter-spacing: 0px;
`;

export const baseRegularXl = css`
  font-family: Kode Mono;
  font-size: 1rem;
  font-weight: 400;
  line-height: 1.25rem;
  letter-spacing: 0px;
`;

export const baseRegularXxl = css`
  font-family: Kode Mono;
  font-size: 1rem;
  font-weight: 400;
  line-height: 1.25rem;
  letter-spacing: 0px;
`;

export const mobileRegularXs = css`
  font-family: Kode Mono;
  font-size: 1rem;
  font-weight: 400;
  line-height: 1.25rem;
  letter-spacing: 0px;
`;

export const mobileRegularSm = css`
  font-family: Kode Mono;
  font-size: 1rem;
  font-weight: 400;
  line-height: 1.25rem;
  letter-spacing: 0px;
`;

export const mobileRegularMd = css`
  font-family: Kode Mono;
  font-size: 1rem;
  font-weight: 400;
  line-height: 1.25rem;
  letter-spacing: 0px;
`;

export const mobileRegularLg = css`
  font-family: Kode Mono;
  font-size: 1rem;
  font-weight: 400;
  line-height: 1.25rem;
  letter-spacing: 0px;
`;

export const mobileRegularXl = css`
  font-family: Kode Mono;
  font-size: 1rem;
  font-weight: 400;
  line-height: 1.25rem;
  letter-spacing: 0px;
`;

export const mobileRegularXxl = css`
  font-family: Kode Mono;
  font-size: 1rem;
  font-weight: 400;
  line-height: 1.25rem;
  letter-spacing: 0px;
`;

export const baseRegularXs = css`
  font-family: Inter;
  font-size: 0.75rem;
  font-weight: 400;
  line-height: 1rem;
  letter-spacing: 0px;
`;

export const baseRegularSm = css`
  font-family: Inter;
  font-size: 0.875rem;
  font-weight: 400;
  line-height: 1.375rem;
  letter-spacing: 0px;
`;

export const baseRegularMd = css`
  font-family: Inter;
  font-size: 1rem;
  font-weight: 400;
  line-height: 1.5rem;
  letter-spacing: 0px;
`;

export const baseRegularLg = css`
  font-family: Inter;
  font-size: 1rem;
  font-weight: 400;
  line-height: 1.5rem;
  letter-spacing: 0px;
`;

export const baseRegularXl = css`
  font-family: Inter;
  font-size: 1rem;
  font-weight: 400;
  line-height: 1.5rem;
  letter-spacing: 0px;
`;

export const baseRegularXxl = css`
  font-family: Inter;
  font-size: 1rem;
  font-weight: 400;
  line-height: 1.5rem;
  letter-spacing: 0px;
`;

export const mobileRegularXs = css`
  font-family: Inter;
  font-size: 1rem;
  font-weight: 400;
  line-height: 1.5rem;
  letter-spacing: 0px;
`;

export const mobileRegularSm = css`
  font-family: Inter;
  font-size: 1rem;
  font-weight: 400;
  line-height: 1.5rem;
  letter-spacing: 0px;
`;

export const mobileRegularMd = css`
  font-family: Inter;
  font-size: 1rem;
  font-weight: 400;
  line-height: 1.5rem;
  letter-spacing: 0px;
`;

export const mobileRegularLg = css`
  font-family: Inter;
  font-size: 1rem;
  font-weight: 400;
  line-height: 1.5rem;
  letter-spacing: 0px;
`;

export const mobileRegularXl = css`
  font-family: Inter;
  font-size: 1rem;
  font-weight: 400;
  line-height: 1.5rem;
  letter-spacing: 0px;
`;

export const mobileRegularXxl = css`
  font-family: Inter;
  font-size: 1rem;
  font-weight: 400;
  line-height: 1.5rem;
  letter-spacing: 0px;
`;

export const smallRegularXs = css`
  font-family: Inter;
  font-size: 0.75rem;
  font-weight: 400;
  line-height: 1rem;
  letter-spacing: 0px;
`;

export const smallRegularSm = css`
  font-family: Inter;
  font-size: 0.75rem;
  font-weight: 400;
  line-height: 1rem;
  letter-spacing: 0px;
`;

export const smallRegularMd = css`
  font-family: Inter;
  font-size: 0.75rem;
  font-weight: 400;
  line-height: 1rem;
  letter-spacing: 0px;
`;

export const smallRegularLg = css`
  font-family: Inter;
  font-size: 0.875rem;
  font-weight: 400;
  line-height: 1.375rem;
  letter-spacing: 0px;
`;

export const smallRegularXl = css`
  font-family: Inter;
  font-size: 0.875rem;
  font-weight: 400;
  line-height: 1.375rem;
  letter-spacing: 0px;
`;

export const smallRegularXxl = css`
  font-family: Inter;
  font-size: 0.875rem;
  font-weight: 400;
  line-height: 1.375rem;
  letter-spacing: 0px;
`;

export const smallBoldXs = css`
  font-family: Inter;
  font-size: 0.75rem;
  font-weight: 500;
  line-height: 1rem;
  letter-spacing: 0px;
`;

export const smallBoldSm = css`
  font-family: Inter;
  font-size: 0.75rem;
  font-weight: 500;
  line-height: 1rem;
  letter-spacing: 0px;
`;

export const smallBoldMd = css`
  font-family: Inter;
  font-size: 0.75rem;
  font-weight: 500;
  line-height: 1rem;
  letter-spacing: 0px;
`;

export const smallBoldLg = css`
  font-family: Inter;
  font-size: 0.875rem;
  font-weight: 500;
  line-height: 1.375rem;
  letter-spacing: 0px;
`;

export const smallBoldXl = css`
  font-family: Inter;
  font-size: 0.875rem;
  font-weight: 500;
  line-height: 1.375rem;
  letter-spacing: 0px;
`;

export const smallBoldXxl = css`
  font-family: Inter;
  font-size: 0.875rem;
  font-weight: 500;
  line-height: 1.375rem;
  letter-spacing: 0px;
`;

export const smallestRegularXs = css`
  font-family: Inter;
  font-size: 0.6875rem;
  font-weight: 400;
  line-height: 1rem;
  letter-spacing: 0px;
`;

export const smallestRegularSm = css`
  font-family: Inter;
  font-size: 0.6875rem;
  font-weight: 400;
  line-height: 1rem;
  letter-spacing: 0px;
`;

export const smallestRegularMd = css`
  font-family: Inter;
  font-size: 0.6875rem;
  font-weight: 400;
  line-height: 1rem;
  letter-spacing: 0px;
`;

export const smallestRegularLg = css`
  font-family: Inter;
  font-size: 0.75rem;
  font-weight: 400;
  line-height: 1.25rem;
  letter-spacing: 0px;
`;

export const smallestRegularXl = css`
  font-family: Inter;
  font-size: 0.75rem;
  font-weight: 400;
  line-height: 1.25rem;
  letter-spacing: 0px;
`;

export const smallestRegularXxl = css`
  font-family: Inter;
  font-size: 0.75rem;
  font-weight: 400;
  line-height: 1.25rem;
  letter-spacing: 0px;
`;

export const smallestBoldXs = css`
  font-family: Inter;
  font-size: 0.6875rem;
  font-weight: 500;
  line-height: 1rem;
  letter-spacing: 0px;
`;

export const smallestBoldSm = css`
  font-family: Inter;
  font-size: 0.6875rem;
  font-weight: 500;
  line-height: 1rem;
  letter-spacing: 0px;
`;

export const smallestBoldMd = css`
  font-family: Inter;
  font-size: 0.6875rem;
  font-weight: 500;
  line-height: 1rem;
  letter-spacing: 0px;
`;

export const smallestBoldLg = css`
  font-family: Inter;
  font-size: 0.75rem;
  font-weight: 500;
  line-height: 1.25rem;
  letter-spacing: 0px;
`;

export const smallestBoldXl = css`
  font-family: Inter;
  font-size: 0.75rem;
  font-weight: 500;
  line-height: 1.25rem;
  letter-spacing: 0px;
`;

export const smallestBoldXxl = css`
  font-family: Inter;
  font-size: 0.75rem;
  font-weight: 500;
  line-height: 1.25rem;
  letter-spacing: 0px;
`;

export const baseRegularXs = css`
  font-family: Inter;
  font-size: 0.875rem;
  font-weight: 400;
  line-height: 1.375rem;
  letter-spacing: 0px;
`;

export const baseRegularSm = css`
  font-family: Inter;
  font-size: 0.875rem;
  font-weight: 400;
  line-height: 1.375rem;
  letter-spacing: 0px;
`;

export const baseRegularMd = css`
  font-family: Inter;
  font-size: 0.875rem;
  font-weight: 400;
  line-height: 1.375rem;
  letter-spacing: 0px;
`;

export const baseRegularLg = css`
  font-family: Inter;
  font-size: 1rem;
  font-weight: 400;
  line-height: 1.5rem;
  letter-spacing: 0px;
`;

export const baseRegularXl = css`
  font-family: Inter;
  font-size: 1rem;
  font-weight: 400;
  line-height: 1.5rem;
  letter-spacing: 0px;
`;

export const baseRegularXxl = css`
  font-family: Inter;
  font-size: 1rem;
  font-weight: 400;
  line-height: 1.5rem;
  letter-spacing: 0px;
`;

export const baseBoldXs = css`
  font-family: Inter;
  font-size: 0.875rem;
  font-weight: 500;
  line-height: 1.375rem;
  letter-spacing: 0px;
`;

export const baseBoldSm = css`
  font-family: Inter;
  font-size: 0.875rem;
  font-weight: 500;
  line-height: 1.375rem;
  letter-spacing: 0px;
`;

export const baseBoldMd = css`
  font-family: Inter;
  font-size: 0.875rem;
  font-weight: 500;
  line-height: 1.375rem;
  letter-spacing: 0px;
`;

export const baseBoldLg = css`
  font-family: Inter;
  font-size: 1rem;
  font-weight: 500;
  line-height: 1.5rem;
  letter-spacing: 0px;
`;

export const baseBoldXl = css`
  font-family: Inter;
  font-size: 1rem;
  font-weight: 500;
  line-height: 1.5rem;
  letter-spacing: 0px;
`;

export const baseBoldXxl = css`
  font-family: Inter;
  font-size: 1rem;
  font-weight: 500;
  line-height: 1.5rem;
  letter-spacing: 0px;
`;

export const largeRegularXs = css`
  font-family: Inter;
  font-size: 1.125rem;
  font-weight: 400;
  line-height: 1.25rem;
  letter-spacing: 0px;
`;

export const largeRegularSm = css`
  font-family: Inter;
  font-size: 1.125rem;
  font-weight: 400;
  line-height: 1.25rem;
  letter-spacing: 0px;
`;

export const largeRegularMd = css`
  font-family: Inter;
  font-size: 1.125rem;
  font-weight: 400;
  line-height: 1.25rem;
  letter-spacing: 0px;
`;

export const largeRegularLg = css`
  font-family: Inter;
  font-size: 1.25rem;
  font-weight: 400;
  line-height: 1.5rem;
  letter-spacing: 0px;
`;

export const largeRegularXl = css`
  font-family: Inter;
  font-size: 1.25rem;
  font-weight: 400;
  line-height: 1.5rem;
  letter-spacing: 0px;
`;

export const largeRegularXxl = css`
  font-family: Inter;
  font-size: 1.25rem;
  font-weight: 400;
  line-height: 1.5rem;
  letter-spacing: 0px;
`;

export const largeBoldXs = css`
  font-family: Inter;
  font-size: 1.125rem;
  font-weight: 500;
  line-height: 1.25rem;
  letter-spacing: 0px;
`;

export const largeBoldSm = css`
  font-family: Inter;
  font-size: 1.125rem;
  font-weight: 500;
  line-height: 1.25rem;
  letter-spacing: 0px;
`;

export const largeBoldMd = css`
  font-family: Inter;
  font-size: 1.125rem;
  font-weight: 500;
  line-height: 1.25rem;
  letter-spacing: 0px;
`;

export const largeBoldLg = css`
  font-family: Inter;
  font-size: 1.25rem;
  font-weight: 500;
  line-height: 1.5rem;
  letter-spacing: 0px;
`;

export const largeBoldXl = css`
  font-family: Inter;
  font-size: 1.25rem;
  font-weight: 500;
  line-height: 1.5rem;
  letter-spacing: 0px;
`;

export const largeBoldXxl = css`
  font-family: Inter;
  font-size: 1.25rem;
  font-weight: 500;
  line-height: 1.5rem;
  letter-spacing: 0px;
`;

export const smallRegularXs = css`
  font-family: Inter;
  font-size: 0.75rem;
  font-weight: 400;
  line-height: 1rem;
  letter-spacing: 0px;
`;

export const smallRegularSm = css`
  font-family: Inter;
  font-size: 0.75rem;
  font-weight: 400;
  line-height: 1rem;
  letter-spacing: 0px;
`;

export const smallRegularMd = css`
  font-family: Inter;
  font-size: 0.75rem;
  font-weight: 400;
  line-height: 1rem;
  letter-spacing: 0px;
`;

export const smallRegularLg = css`
  font-family: Inter;
  font-size: 0.875rem;
  font-weight: 400;
  line-height: 1rem;
  letter-spacing: 0px;
`;

export const smallRegularXl = css`
  font-family: Inter;
  font-size: 0.875rem;
  font-weight: 400;
  line-height: 1rem;
  letter-spacing: 0px;
`;

export const smallRegularXxl = css`
  font-family: Inter;
  font-size: 0.875rem;
  font-weight: 400;
  line-height: 1rem;
  letter-spacing: 0px;
`;

export const smallBoldXs = css`
  font-family: Inter;
  font-size: 0.75rem;
  font-weight: 500;
  line-height: 1rem;
  letter-spacing: 0px;
`;

export const smallBoldSm = css`
  font-family: Inter;
  font-size: 0.75rem;
  font-weight: 500;
  line-height: 1rem;
  letter-spacing: 0px;
`;

export const smallBoldMd = css`
  font-family: Inter;
  font-size: 0.75rem;
  font-weight: 500;
  line-height: 1rem;
  letter-spacing: 0px;
`;

export const smallBoldLg = css`
  font-family: Inter;
  font-size: 0.875rem;
  font-weight: 500;
  line-height: 1rem;
  letter-spacing: 0px;
`;

export const smallBoldXl = css`
  font-family: Inter;
  font-size: 0.875rem;
  font-weight: 500;
  line-height: 1rem;
  letter-spacing: 0px;
`;

export const smallBoldXxl = css`
  font-family: Inter;
  font-size: 0.875rem;
  font-weight: 500;
  line-height: 1rem;
  letter-spacing: 0px;
`;

export const smallestRegularXs = css`
  font-family: Inter;
  font-size: 0.6875rem;
  font-weight: 400;
  line-height: 0.875rem;
  letter-spacing: 0px;
`;

export const smallestRegularSm = css`
  font-family: Inter;
  font-size: 0.6875rem;
  font-weight: 400;
  line-height: 0.875rem;
  letter-spacing: 0px;
`;

export const smallestRegularMd = css`
  font-family: Inter;
  font-size: 0.6875rem;
  font-weight: 400;
  line-height: 0.875rem;
  letter-spacing: 0px;
`;

export const smallestRegularLg = css`
  font-family: Inter;
  font-size: 0.75rem;
  font-weight: 400;
  line-height: 1rem;
  letter-spacing: 0px;
`;

export const smallestRegularXl = css`
  font-family: Inter;
  font-size: 0.75rem;
  font-weight: 400;
  line-height: 1rem;
  letter-spacing: 0px;
`;

export const smallestRegularXxl = css`
  font-family: Inter;
  font-size: 0.75rem;
  font-weight: 400;
  line-height: 1rem;
  letter-spacing: 0px;
`;

export const smallestBoldXs = css`
  font-family: Inter;
  font-size: 0.6875rem;
  font-weight: 500;
  line-height: 0.875rem;
  letter-spacing: 0px;
`;

export const smallestBoldSm = css`
  font-family: Inter;
  font-size: 0.6875rem;
  font-weight: 500;
  line-height: 0.875rem;
  letter-spacing: 0px;
`;

export const smallestBoldMd = css`
  font-family: Inter;
  font-size: 0.6875rem;
  font-weight: 500;
  line-height: 0.875rem;
  letter-spacing: 0px;
`;

export const smallestBoldLg = css`
  font-family: Inter;
  font-size: 0.75rem;
  font-weight: 500;
  line-height: 1rem;
  letter-spacing: 0px;
`;

export const smallestBoldXl = css`
  font-family: Inter;
  font-size: 0.75rem;
  font-weight: 500;
  line-height: 1rem;
  letter-spacing: 0px;
`;

export const smallestBoldXxl = css`
  font-family: Inter;
  font-size: 0.75rem;
  font-weight: 500;
  line-height: 1rem;
  letter-spacing: 0px;
`;

export const baseRegularXs = css`
  font-family: Inter;
  font-size: 0.875rem;
  font-weight: 400;
  line-height: 1.125rem;
  letter-spacing: 0px;
`;

export const baseRegularSm = css`
  font-family: Inter;
  font-size: 0.875rem;
  font-weight: 400;
  line-height: 1.125rem;
  letter-spacing: 0px;
`;

export const baseRegularMd = css`
  font-family: Inter;
  font-size: 0.875rem;
  font-weight: 400;
  line-height: 1.125rem;
  letter-spacing: 0px;
`;

export const baseRegularLg = css`
  font-family: Inter;
  font-size: 1rem;
  font-weight: 400;
  line-height: 1.25rem;
  letter-spacing: 0px;
`;

export const baseRegularXl = css`
  font-family: Inter;
  font-size: 1rem;
  font-weight: 400;
  line-height: 1.25rem;
  letter-spacing: 0px;
`;

export const baseRegularXxl = css`
  font-family: Inter;
  font-size: 1rem;
  font-weight: 400;
  line-height: 1.25rem;
  letter-spacing: 0px;
`;

export const baseBoldXs = css`
  font-family: Inter;
  font-size: 0.875rem;
  font-weight: 500;
  line-height: 1.125rem;
  letter-spacing: 0px;
`;

export const baseBoldSm = css`
  font-family: Inter;
  font-size: 0.875rem;
  font-weight: 500;
  line-height: 1.125rem;
  letter-spacing: 0px;
`;

export const baseBoldMd = css`
  font-family: Inter;
  font-size: 0.875rem;
  font-weight: 500;
  line-height: 1.125rem;
  letter-spacing: 0px;
`;

export const baseBoldLg = css`
  font-family: Inter;
  font-size: 1rem;
  font-weight: 500;
  line-height: 1.25rem;
  letter-spacing: 0px;
`;

export const baseBoldXl = css`
  font-family: Inter;
  font-size: 1rem;
  font-weight: 500;
  line-height: 1.25rem;
  letter-spacing: 0px;
`;

export const baseBoldXxl = css`
  font-family: Inter;
  font-size: 1rem;
  font-weight: 500;
  line-height: 1.25rem;
  letter-spacing: 0px;
`;
